/*
 * Copyright (c) 2024-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "nativeFontNdk.h"

napi_property_descriptor desc[] = {
    {"oHDrawingMatchFontDescriptors001", nullptr, OHDrawingMatchFontDescriptors001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingMatchFontDescriptors002", nullptr, OHDrawingMatchFontDescriptors002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingMatchFontDescriptors003", nullptr, OHDrawingMatchFontDescriptors003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingMatchFontDescriptors004", nullptr, OHDrawingMatchFontDescriptors004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingMatchFontDescriptors005", nullptr, OHDrawingMatchFontDescriptors005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontDescriptorByFullName001", nullptr, OHDrawingGetFontDescriptorByFullName001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontDescriptorByFullName002", nullptr, OHDrawingGetFontDescriptorByFullName002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontDescriptorByFullName003", nullptr, OHDrawingGetFontDescriptorByFullName003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontDescriptorByFullName004", nullptr, OHDrawingGetFontDescriptorByFullName004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontFullNamesByType001", nullptr, OHDrawingGetSystemFontFullNamesByType001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontFullNamesByType002", nullptr, OHDrawingGetSystemFontFullNamesByType002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontFullNamesByType003", nullptr, OHDrawingGetSystemFontFullNamesByType003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontFullNamesByType004", nullptr, OHDrawingGetSystemFontFullNamesByType004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontFullNameByIndex001", nullptr, OHDrawingGetSystemFontFullNameByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateLineTypography001", nullptr, OHDrawingCreateLineTypography001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateLineTypography002", nullptr, OHDrawingCreateLineTypography002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateLineTypography003", nullptr, OHDrawingCreateLineTypography003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateLineTypography004", nullptr, OHDrawingCreateLineTypography004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyGetLineBreak001", nullptr, OHDrawingLineTypographyGetLineBreak001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyGetLineBreak002", nullptr, OHDrawingLineTypographyGetLineBreak002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyGetLineBreak003", nullptr, OHDrawingLineTypographyGetLineBreak003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyGetLineBreak004", nullptr, OHDrawingLineTypographyGetLineBreak004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyGetLineBreak005", nullptr, OHDrawingLineTypographyGetLineBreak005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine001", nullptr, OHDrawingLineTypographyCreateLine001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine002", nullptr, OHDrawingLineTypographyCreateLine002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine003", nullptr, OHDrawingLineTypographyCreateLine003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine004", nullptr, OHDrawingLineTypographyCreateLine004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine005", nullptr, OHDrawingLineTypographyCreateLine005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine006", nullptr, OHDrawingLineTypographyCreateLine006,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetBounds001", nullptr, OHDrawingFontGetBounds001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetBounds002", nullptr, OHDrawingFontGetBounds002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetBounds003", nullptr, OHDrawingFontGetBounds003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRectDestroyArray001", nullptr, OHDrawingRectDestroyArray001,
     nullptr, nullptr, nullptr, napi_default, nullptr},

    // cpp2中的用例
    {"oHDrawingFontGetPathForGlyph001", nullptr, OHDrawingFontGetPathForGlyph001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetPathForGlyph002", nullptr, OHDrawingFontGetPathForGlyph002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetPathForGlyph003", nullptr, OHDrawingFontGetPathForGlyph003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetPathForGlyph004", nullptr, OHDrawingFontGetPathForGlyph004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRectGetArraySize001", nullptr, OHDrawingRectGetArraySize001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRectGetArraySize002", nullptr, OHDrawingRectGetArraySize002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRectGetArrayElement001", nullptr, OHDrawingRectGetArrayElement001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateTextTab001", nullptr, OHDrawingCreateTextTab001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextTabAlignment001", nullptr, OHDrawingGetTextTabAlignment001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextTabLocation001", nullptr, OHDrawingGetTextTabLocation001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontGetTextPath001", nullptr, OHDrawingFontGetTextPath001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetDrawingArraySize001", nullptr, OHDrawingGetDrawingArraySize001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetTextLines001", nullptr, OHDrawingTypographyGetTextLines001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetTextLines002", nullptr, OHDrawingTypographyGetTextLines002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingDestroyTextLine001", nullptr, OHDrawingDestroyTextLine001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextLineByIndex001", nullptr, OHDrawingGetTextLineByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetTextRange001", nullptr, OHDrawingTextLineGetTextRange001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetGlyphRuns001", nullptr, OHDrawingTextLineGetGlyphRuns001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingDestroyRuns001", nullptr, OHDrawingDestroyRuns001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunByIndex001", nullptr, OHDrawingGetRunByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLinePaint001", nullptr, OHDrawingTextLinePaint001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineCreateTruncatedLine001", nullptr, OHDrawingTextLineCreateTruncatedLine001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetTypographicBounds001", nullptr, OHDrawingTextLineGetTypographicBounds001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetImageBounds001", nullptr, OHDrawingTextLineGetImageBounds001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetTrailingSpaceWidth001", nullptr, OHDrawingTextLineGetTrailingSpaceWidth001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetStringIndexForPosition001", nullptr, OHDrawingTextLineGetStringIndexForPosition001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetOffsetForStringIndex001", nullptr, OHDrawingTextLineGetOffsetForStringIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextLineGetAlignmentOffset001", nullptr, OHDrawingTextLineGetAlignmentOffset001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunGlyphCount001", nullptr, OHDrawingGetRunGlyphCount001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunStringRange001", nullptr, OHDrawingGetRunStringRange001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunTypographicBounds001", nullptr, OHDrawingGetRunTypographicBounds001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunStringIndicesByIndex001", nullptr, OHDrawingGetRunStringIndicesByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunImageBounds001", nullptr, OHDrawingGetRunImageBounds001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunGlyphsByIndex001", nullptr, OHDrawingGetRunGlyphsByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunPositions001", nullptr, OHDrawingGetRunPositions001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontCollectionGlobalInstance001", nullptr, OHDrawingGetFontCollectionGlobalInstance001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleBadgeType001", nullptr, OHDrawingSetTextStyleBadgeType001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleBadgeType002", nullptr, OHDrawingSetTextStyleBadgeType002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText001", nullptr, OHDrawingTypographyHandlerAddEncodedText001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText002", nullptr, OHDrawingTypographyHandlerAddEncodedText002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText003", nullptr, OHDrawingTypographyHandlerAddEncodedText003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText004", nullptr, OHDrawingTypographyHandlerAddEncodedText004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText005", nullptr, OHDrawingTypographyHandlerAddEncodedText005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText006", nullptr, OHDrawingTypographyHandlerAddEncodedText006,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText007", nullptr, OHDrawingTypographyHandlerAddEncodedText007,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText008", nullptr, OHDrawingTypographyHandlerAddEncodedText008,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyHandlerAddEncodedText009", nullptr, OHDrawingTypographyHandlerAddEncodedText009,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRun001", nullptr, OHDrawingGetRun001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble001", nullptr, OHDrawingSetTypographyStyleAttributeDouble001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeInt001", nullptr, OHDrawingSetTypographyStyleAttributeInt001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeDouble001", nullptr, OHDrawingSetTextStyleAttributeDouble001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeDouble002", nullptr, OHDrawingSetTextStyleAttributeDouble002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeDouble003", nullptr, OHDrawingSetTextStyleAttributeDouble003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeDouble004", nullptr, OHDrawingSetTextStyleAttributeDouble004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeInt001", nullptr, OHDrawingSetTextStyleAttributeInt001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorsFromPath001", nullptr, OHDrawingGetFontFullDescriptorsFromPath001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorsFromPath002", nullptr, OHDrawingGetFontFullDescriptorsFromPath002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorsFromPath003", nullptr, OHDrawingGetFontFullDescriptorsFromPath003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorAttributeString001", nullptr, OHDrawingGetFontFullDescriptorAttributeString001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorAttributeString002", nullptr, OHDrawingGetFontFullDescriptorAttributeString002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorAttributeString003", nullptr, OHDrawingGetFontFullDescriptorAttributeString003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorByIndex001", nullptr, OHDrawingGetFontFullDescriptorByIndex001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorAttributeInt001", nullptr, OHDrawingGetFontFullDescriptorAttributeInt001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorAttributeInt002", nullptr, OHDrawingGetFontFullDescriptorAttributeInt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorFromStream001", nullptr, OHDrawingGetFontFullDescriptorFromStream001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorFromStream002", nullptr, OHDrawingGetFontFullDescriptorFromStream002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetFontFullDescriptorFromStream003", nullptr, OHDrawingGetFontFullDescriptorFromStream003,
        nullptr, nullptr, nullptr, napi_default, nullptr},

    // cpp3中的用例
    {"oHDrawingTypographyIsEllipsized001", nullptr, OHDrawingTypographyIsEllipsized001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyIsEllipsized002", nullptr, OHDrawingTypographyIsEllipsized002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyIsEllipsized003", nullptr, OHDrawingTypographyIsEllipsized003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyIsLineUnlimited001", nullptr, OHDrawingTypographyIsLineUnlimited001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyIsLineUnlimited002", nullptr, OHDrawingTypographyIsLineUnlimited002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyIsLineUnlimited003", nullptr, OHDrawingTypographyIsLineUnlimited003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontParserGetFontByName001", nullptr, OHDrawingFontParserGetFontByName001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingCreateFontDescriptor001", nullptr, OHDrawingCreateFontDescriptor001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineTextRange001", nullptr, OHDrawingTypographyGetLineTextRange001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineTextRange002", nullptr, OHDrawingTypographyGetLineTextRange002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineTextRange003", nullptr, OHDrawingTypographyGetLineTextRange003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextVerticalAlignment001", nullptr, OHDrawingTextVerticalAlignment001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextVerticalAlignment002", nullptr, OHDrawingTextVerticalAlignment002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeInt002", nullptr, OHDrawingSetTypographyStyleAttributeInt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble002", nullptr, OHDrawingSetTypographyStyleAttributeDouble002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble003", nullptr, OHDrawingSetTypographyStyleAttributeDouble003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextStyleAttributeInt001", nullptr, OHDrawingGetTextStyleAttributeInt001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetRunGlyphAdvanceByIndex001", nullptr, OHDrawingGetRunGlyphAdvanceByIndex001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingLineTypographyCreateLine007", nullptr, OHDrawingLineTypographyCreateLine007,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingUnregisterFont001", nullptr, OHDrawingUnregisterFont001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingFontStyleSetGetStyle001", nullptr, OHDrawingFontStyleSetGetStyle001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleIsHintEnabled001", nullptr, OHDrawingTypographyStyleIsHintEnabled001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleIsHintEnabled002", nullptr, OHDrawingTypographyStyleIsHintEnabled002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetSystemFontConfigInfo001", nullptr, OHDrawingGetSystemFontConfigInfo001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble007", nullptr, OHDrawingSetTypographyStyleAttributeDouble007,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeInt005", nullptr, OHDrawingSetTypographyStyleAttributeInt005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeInt002", nullptr, OHDrawingSetTextStyleAttributeInt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeInt003", nullptr, OHDrawingSetTextStyleAttributeInt003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextStyleAttributeInt002", nullptr, OHDrawingGetTextStyleAttributeInt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble004", nullptr, OHDrawingSetTypographyStyleAttributeDouble004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble005", nullptr, OHDrawingSetTypographyStyleAttributeDouble005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeDouble006", nullptr, OHDrawingSetTypographyStyleAttributeDouble006,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTypographyStyleAttributeDouble001", nullptr, OHDrawingGetTypographyStyleAttributeDouble001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTypographyStyleAttributeInt001", nullptr, OHDrawingGetTypographyStyleAttributeInt001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeInt003", nullptr, OHDrawingSetTypographyStyleAttributeInt003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTypographyStyleAttributeInt004", nullptr, OHDrawingSetTypographyStyleAttributeInt004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextStyleAttributeDouble001", nullptr, OHDrawingGetTextStyleAttributeDouble001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTypographyStyleAttributeInt002", nullptr, OHDrawingGetTypographyStyleAttributeInt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTypographyStyleAttributeInt003", nullptr, OHDrawingGetTypographyStyleAttributeInt003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleGetStrutStyle001", nullptr, OHDrawingTypographyStyleGetStrutStyle001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyTextlineStyleGetFontWeight001", nullptr, OHDrawingTypographyTextlineStyleGetFontWeight001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyTextlineStyleGetFontStyle001", nullptr, OHDrawingTypographyTextlineStyleGetFontStyle001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetTextAlign001", nullptr, OHDrawingTypographyGetTextAlign001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingGetTextTabAlignment002", nullptr, OHDrawingGetTextTabAlignment002,
        nullptr, nullptr, nullptr, napi_default, nullptr},

    // cpp4中的用例
    {"oHDrawingTextStyleGetFontMetrics001", nullptr, OHDrawingTextStyleGetFontMetrics001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontMetrics002", nullptr, OHDrawingTextStyleGetFontMetrics002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontMetrics003", nullptr, OHDrawingTextStyleGetFontMetrics003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontMetrics004", nullptr, OHDrawingTextStyleGetFontMetrics004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontMetrics005", nullptr, OHDrawingTextStyleGetFontMetrics005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineInfo001", nullptr, OHDrawingTypographyGetLineInfo001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineInfo002", nullptr, OHDrawingTypographyGetLineInfo002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineInfo003", nullptr, OHDrawingTypographyGetLineInfo003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineInfo004", nullptr, OHDrawingTypographyGetLineInfo004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineInfo005", nullptr, OHDrawingTypographyGetLineInfo005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetShadowWithIndex001", nullptr, OHDrawingTextStyleGetShadowWithIndex001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetShadowWithIndex002", nullptr, OHDrawingTextStyleGetShadowWithIndex002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetShadowWithIndex003", nullptr, OHDrawingTextStyleGetShadowWithIndex003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetShadowWithIndex004", nullptr, OHDrawingTextStyleGetShadowWithIndex004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyTextGetHeightBehavior001", nullptr, OHDrawingTypographyTextGetHeightBehavior001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyTextGetHeightBehavior002", nullptr, OHDrawingTypographyTextGetHeightBehavior002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetDecorationStyle001", nullptr, OHDrawingTextStyleGetDecorationStyle001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetDecorationStyle002", nullptr, OHDrawingTextStyleGetDecorationStyle002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontWeight001", nullptr, OHDrawingTextStyleGetFontWeight001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontWeight002", nullptr, OHDrawingTextStyleGetFontWeight002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontStyle001", nullptr, OHDrawingTextStyleGetFontStyle001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetFontStyle002", nullptr, OHDrawingTextStyleGetFontStyle002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetBaseline001", nullptr, OHDrawingTextStyleGetBaseline001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetBaseline002", nullptr, OHDrawingTextStyleGetBaseline002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetHalfLeading001", nullptr, OHDrawingTextStyleGetHalfLeading001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleGetHalfLeading002", nullptr, OHDrawingTextStyleGetHalfLeading002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleIsPlaceholder001", nullptr, OHDrawingTextStyleIsPlaceholder001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTextStyleIsPlaceholder002", nullptr, OHDrawingTextStyleIsPlaceholder002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleGetEffectiveAlignment001", nullptr, OHDrawingTypographyStyleGetEffectiveAlignment001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleGetEffectiveAlignment002", nullptr, OHDrawingTypographyStyleGetEffectiveAlignment002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyDidExceedMaxLines001", nullptr, OHDrawingTypographyDidExceedMaxLines001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyDidExceedMaxLines002", nullptr, OHDrawingTypographyDidExceedMaxLines002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyDidExceedMaxLines003", nullptr, OHDrawingTypographyDidExceedMaxLines003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetRectsForRange001", nullptr, OHDrawingTypographyGetRectsForRange001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetGlyphPositionAtCoordinate001", nullptr, OHDrawingTypographyGetGlyphPositionAtCoordinate001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetGlyphPositionAtCoordinate002", nullptr, OHDrawingTypographyGetGlyphPositionAtCoordinate002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetGlyphPositionAtCoordinateWithCluster001", nullptr,
        OHDrawingTypographyGetGlyphPositionAtCoordinateWithCluster001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetWordBoundary001", nullptr, OHDrawingTypographyGetWordBoundary001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineMetricsAt001", nullptr, OHDrawingTypographyGetLineMetricsAt001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineMetricsAt002", nullptr, OHDrawingTypographyGetLineMetricsAt002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineMetricsAt003", nullptr, OHDrawingTypographyGetLineMetricsAt003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyGetLineMetricsAt004", nullptr, OHDrawingTypographyGetLineMetricsAt004,
        nullptr, nullptr, nullptr, napi_default, nullptr},

    // cpp5中的用例
    {"oHDrawingSetTextStyleAttributeInt004", nullptr, OHDrawingSetTextStyleAttributeInt004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyDidExceedMaxLines004", nullptr, OHDrawingTypographyDidExceedMaxLines004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingTypographyStyleGetEffectiveAlignment003", nullptr, OHDrawingTypographyStyleGetEffectiveAlignment003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingSetTextStyleAttributeDouble005", nullptr, OHDrawingSetTextStyleAttributeDouble005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromPath001", nullptr, OHDrawingIsFontSupportedFromPath001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromPath002", nullptr, OHDrawingIsFontSupportedFromPath002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromPath003", nullptr, OHDrawingIsFontSupportedFromPath003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromPath004", nullptr, OHDrawingIsFontSupportedFromPath004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer001", nullptr, OHDrawingIsFontSupportedFromBuffer001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer002", nullptr, OHDrawingIsFontSupportedFromBuffer002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer003", nullptr, OHDrawingIsFontSupportedFromBuffer003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer004", nullptr, OHDrawingIsFontSupportedFromBuffer004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer005", nullptr, OHDrawingIsFontSupportedFromBuffer005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer006", nullptr, OHDrawingIsFontSupportedFromBuffer006,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer007", nullptr, OHDrawingIsFontSupportedFromBuffer007,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingIsFontSupportedFromBuffer008", nullptr, OHDrawingIsFontSupportedFromBuffer008,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingErrorFileNotFound001", nullptr, OHDrawingErrorFileNotFound001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex001", nullptr, OHDrawingRegisterFontByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex002", nullptr, OHDrawingRegisterFontByIndex002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex003", nullptr, OHDrawingRegisterFontByIndex003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex004", nullptr, OHDrawingRegisterFontByIndex004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex005", nullptr, OHDrawingRegisterFontByIndex005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex006", nullptr, OHDrawingRegisterFontByIndex006,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex007", nullptr, OHDrawingRegisterFontByIndex007,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex008", nullptr, OHDrawingRegisterFontByIndex008,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex009", nullptr, OHDrawingRegisterFontByIndex009,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontByIndex010", nullptr, OHDrawingRegisterFontByIndex010,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex001", nullptr, OHDrawingRegisterFontBufferByIndex001,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex002", nullptr, OHDrawingRegisterFontBufferByIndex002,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex003", nullptr, OHDrawingRegisterFontBufferByIndex003,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex004", nullptr, OHDrawingRegisterFontBufferByIndex004,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex005", nullptr, OHDrawingRegisterFontBufferByIndex005,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex006", nullptr, OHDrawingRegisterFontBufferByIndex006,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex007", nullptr, OHDrawingRegisterFontBufferByIndex007,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex008", nullptr, OHDrawingRegisterFontBufferByIndex008,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex009", nullptr, OHDrawingRegisterFontBufferByIndex009,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"oHDrawingRegisterFontBufferByIndex010", nullptr, OHDrawingRegisterFontBufferByIndex010,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    // 字符串属性ID测试
    {"fullDescriptorAttrSLocalPostscriptName001", nullptr, FullDescriptorAttrSLocalPostscriptName001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLocalPostscriptName002", nullptr, FullDescriptorAttrSLocalPostscriptName002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLocalFullName001", nullptr, FullDescriptorAttrSLocalFullName001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLocalFullName002", nullptr, FullDescriptorAttrSLocalFullName002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLocalFamilyName001", nullptr, FullDescriptorAttrSLocalFamilyName001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLocalSubFamilyName001", nullptr, FullDescriptorAttrSLocalSubFamilyName001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSVersion001", nullptr, FullDescriptorAttrSVersion001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSVersion002", nullptr, FullDescriptorAttrSVersion002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSManufacture001", nullptr, FullDescriptorAttrSManufacture001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSCopyright001", nullptr, FullDescriptorAttrSCopyright001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSTrademark001", nullptr, FullDescriptorAttrSTrademark001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"fullDescriptorAttrSLicense001", nullptr, FullDescriptorAttrSLicense001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    // 整数属性ID测试
    {"fullDescriptorAttrIIndex001", nullptr, FullDescriptorAttrIIndex001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromFile001", nullptr, OHDrawingGetFontUnicodeArrayFromFile001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromFile002", nullptr, OHDrawingGetFontUnicodeArrayFromFile002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromFile003", nullptr, OHDrawingGetFontUnicodeArrayFromFile003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromFile004", nullptr, OHDrawingGetFontUnicodeArrayFromFile004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromFile005", nullptr, OHDrawingGetFontUnicodeArrayFromFile005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromBuffer001", nullptr, OHDrawingGetFontUnicodeArrayFromBuffer001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontUnicodeArrayFromBuffer002", nullptr, OHDrawingGetFontUnicodeArrayFromBuffer002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontCountFromFile001", nullptr, OHDrawingGetFontCountFromFile001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontCountFromFile002", nullptr, OHDrawingGetFontCountFromFile002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontCountFromBuffer001", nullptr, OHDrawingGetFontCountFromBuffer001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontCountFromBuffer002", nullptr, OHDrawingGetFontCountFromBuffer002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontPathsByType001", nullptr, OHDrawingGetFontPathsByType001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontPathsByType002", nullptr, OHDrawingGetFontPathsByType002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetFontPathsByType003", nullptr, OHDrawingGetFontPathsByType003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool001", nullptr, OHDrawingSetTypographyStyleAttributeBool001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool002", nullptr, OHDrawingSetTypographyStyleAttributeBool002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool003", nullptr, OHDrawingSetTypographyStyleAttributeBool003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool004", nullptr, OHDrawingSetTypographyStyleAttributeBool004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool005", nullptr, OHDrawingSetTypographyStyleAttributeBool005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingSetTypographyStyleAttributeBool006", nullptr, OHDrawingSetTypographyStyleAttributeBool006,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetTypographyStyleAttributeBool001", nullptr, OHDrawingGetTypographyStyleAttributeBool001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetTypographyStyleAttributeBool002", nullptr, OHDrawingGetTypographyStyleAttributeBool002,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetTypographyStyleAttributeBool003", nullptr, OHDrawingGetTypographyStyleAttributeBool003,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetTypographyStyleAttributeBool004", nullptr, OHDrawingGetTypographyStyleAttributeBool004,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingGetTypographyStyleAttributeBool005", nullptr, OHDrawingGetTypographyStyleAttributeBool005,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingDestroyPositionAndAffinity001", nullptr, OHDrawingDestroyPositionAndAffinity001,
        nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ohDrawingDestroyPositionAndAffinity002", nullptr, OHDrawingDestroyPositionAndAffinity002,
        nullptr, nullptr, nullptr, napi_default, nullptr},

};

EXTERN_C_START
static napi_value Init(napi_env env, napi_value exports)
{
    napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc);
    return exports;
}
EXTERN_C_END

static napi_module demoModule = {
    .nm_version = 1,
    .nm_flags = 0,
    .nm_filename = nullptr,
    .nm_register_func = Init,
    .nm_modname = "nativeFontNdk",
    .nm_priv = ((void *)0),
    .reserved = {0},
};

extern "C" __attribute__((constructor)) void RegisterEntryModule(void) { napi_module_register(&demoModule); }