/*
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <climits>
#include <gtest/gtest.h>
#include "../Khrgles32BaseFunc.h"
#include "../ActsGles32KhrMainUncover0001TestSuite.h"
#include "shrinkdefine.h"

using namespace std;
using namespace testing::ext;
using namespace OHOS;

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000102,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000103,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000104,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000105,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000106,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000107,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000108,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000109,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000110,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000111,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000112,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000113,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000114,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000115,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000116,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000117,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000118,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000119,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000120,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000121,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000122,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000123,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000124,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000125,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000126,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000127,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000128,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000129,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000130,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000131,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000132,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000133,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000134,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000135,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000136,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000137,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000138,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000139,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000140,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000141,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVer",
 "tices_Position_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000142,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_",
 "Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000143,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_",
 "Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000144,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000145,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000146,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000147,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posi",
 "tion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000148,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVer",
 "tices_Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000149,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVe",
 "rtices_Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000150,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posi",
 "tion_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000151,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000152,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position_",
 "PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000153,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000154,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000155,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000156,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000157,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000158,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000159,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000160,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000161,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000162,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000163,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000164,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000165,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000166,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000167,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000168,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000169,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000170,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000171,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000172,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles32KhrMainUncover0001TestSuite, TestCase_000173,
 "KHR-GLES32.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing__point_mode_enabled");
