/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "include/CryptoFrameworkSymCipherTest.h"

namespace Unittest::CryptoFramework {

SymCipherSpec g_symCipherData[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|NoPadding")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|NoPadding")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|NoPadding")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|ECB|NoPadding")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CBC|NoPadding")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|OFB|NoPadding")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CFB|NoPadding")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|ECB|NoPadding")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CBC|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CTR|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|OFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB128|NoPadding")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS5")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}, // 25
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS5")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS5")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}, // 30
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}, // 39
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|ECB|PKCS5")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}, // 40
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CBC|PKCS5")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|OFB|PKCS5")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CFB|PKCS5")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|ECB|PKCS5")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CBC|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CTR|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|OFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB128|PKCS5")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},  // 49

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS7")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS7")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|ECB|PKCS7")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|ECB|PKCS7")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CBC|PKCS7")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|OFB|PKCS7")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("3DES192|CFB|PKCS7")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|ECB|PKCS7")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CBC|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CTR|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|OFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|CFB128|PKCS7")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20")),
        16, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

SymCipherSpec g_symAesWrapCipherData[] = {
    /* aes wrap with iv */
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128-WRAP")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192-WRAP")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256-WRAP")),
        8, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false},
    /* aes wrap without iv */
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128-WRAP")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192-WRAP")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256-WRAP")),
        0, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, false}
};

SymCipherSpec g_symChaCha20Poly1305CipherData[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20|Poly1305")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

SymCipherSpec g_symCipherGCMData[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|GCM|NoPadding")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|GCM|NoPadding")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|GCM|NoPadding")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|GCM|NoPadding")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|GCM|PKCS5")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|GCM|PKCS5")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|GCM|PKCS5")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|GCM|PKCS5")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|GCM|PKCS7")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|GCM|PKCS7")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|GCM|PKCS7")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("SM4_128|GCM|PKCS7")),
        12, 16, 16, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

SymCipherSpec g_symCipherCCMData[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CCM|NoPadding")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|CCM|NoPadding")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|CCM|NoPadding")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CCM|PKCS5")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|CCM|PKCS5")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|CCM|PKCS5")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},

    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CCM|PKCS7")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES192|CCM|PKCS7")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES256")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES256|CCM|PKCS7")),
        7, 8, 12, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

SymCipherSpec g_symCipherIvError[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|NoPadding")),
        15, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CBC|NoPadding")),
        17, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|NoPadding")),
        15, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CTR|NoPadding")),
        17, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|NoPadding")),
        15, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|CFB|NoPadding")),
        17, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES128")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|NoPadding")),
        15, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true},
    {reinterpret_cast<uint8_t*>(const_cast<char*>("AES192")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("AES128|OFB|NoPadding")),
        17, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

SymCipherSpec g_chaCha20IvError[] = {
    {reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20")),
        reinterpret_cast<uint8_t*>(const_cast<char*>("ChaCha20")),
        15, 0, 0, OH_CRYPTO_SYM_CIPHER_TEST_DATA_SIZE, true}
};

}

