/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "common/common.h"
#include "renderNode/RenderNodeAttributeTest.cpp"
#include "renderNode/RenderNodeTest.cpp"
#include "renderNodeUtils/renderNodeUtils.cpp"
#include "renderNodeUtils/RenderNodeParamTest.cpp"
#include "drag/DragEventFuncTest.h"

namespace ArkUICapiTest
{
    EXTERN_C_START
    static napi_value Init(napi_env env, napi_value exports)
    {
        if ((env == nullptr) || (exports == nullptr))
        {
            OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_PRINT_DOMAIN, "Init", "env or exports is null");
            return nullptr;
        }

        napi_property_descriptor desc[] = {
            {"TestBackgroundColor", nullptr, TestBackgroundColor, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"dragEventFuncTest001", nullptr, DragEventFuncTest::DragEventFuncTest001, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest002", nullptr, DragEventFuncTest::DragEventFuncTest002, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest003", nullptr, DragEventFuncTest::DragEventFuncTest003, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest004", nullptr, DragEventFuncTest::DragEventFuncTest004, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest005", nullptr, DragEventFuncTest::DragEventFuncTest005, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest006", nullptr, DragEventFuncTest::DragEventFuncTest006, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest007", nullptr, DragEventFuncTest::DragEventFuncTest007, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest008", nullptr, DragEventFuncTest::DragEventFuncTest008, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest009", nullptr, DragEventFuncTest::DragEventFuncTest009, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest010", nullptr, DragEventFuncTest::DragEventFuncTest010, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest011", nullptr, DragEventFuncTest::DragEventFuncTest011, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest012", nullptr, DragEventFuncTest::DragEventFuncTest012, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest013", nullptr, DragEventFuncTest::DragEventFuncTest013, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest015", nullptr, DragEventFuncTest::DragEventFuncTest015, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest016", nullptr, DragEventFuncTest::DragEventFuncTest016, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest017", nullptr, DragEventFuncTest::DragEventFuncTest017, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest018", nullptr, DragEventFuncTest::dragEventFuncTest018, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest019", nullptr, DragEventFuncTest::dragEventFuncTest019, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest020", nullptr, DragEventFuncTest::dragEventFuncTest020, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest021", nullptr, DragEventFuncTest::dragEventFuncTest021, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest022", nullptr, DragEventFuncTest::dragEventFuncTest022, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest023", nullptr, DragEventFuncTest::dragEventFuncTest023, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest024", nullptr, DragEventFuncTest::dragEventFuncTest024, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest026", nullptr, DragEventFuncTest::dragEventFuncTest026, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest027", nullptr, DragEventFuncTest::dragEventFuncTest027, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest028", nullptr, DragEventFuncTest::dragEventFuncTest028, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest029", nullptr, DragEventFuncTest::dragEventFuncTest029, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest030", nullptr, DragEventFuncTest::dragEventFuncTest030, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest031", nullptr, DragEventFuncTest::dragEventFuncTest031, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest032", nullptr, DragEventFuncTest::dragEventFuncTest032, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest033", nullptr, DragEventFuncTest::dragEventFuncTest033, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest034", nullptr, DragEventFuncTest::dragEventFuncTest034, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest035", nullptr, DragEventFuncTest::dragEventFuncTest035, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest036", nullptr, DragEventFuncTest::dragEventFuncTest036, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest038", nullptr, DragEventFuncTest::dragEventFuncTest038, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"dragEventFuncTest040", nullptr, DragEventFuncTest::dragEventFuncTest040, nullptr, nullptr, nullptr, 
            napi_default, nullptr},
            {"TestBorderColor", nullptr, TestBorderColor, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestBorderRadius", nullptr, TestBorderRadius, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestBorderStyle", nullptr, TestBorderStyle, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestBorderWidth", nullptr, TestBorderWidth, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestBounds", nullptr, TestBounds, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestClipToBounds", nullptr, TestClipToBounds, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestClipToFrame", nullptr, TestClipToFrame, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestOpacity", nullptr, TestOpacity, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestPivot", nullptr, TestPivot, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestPosition", nullptr, TestPosition, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestRotation", nullptr, TestRotation, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestScale", nullptr, TestScale, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestSetDrawRegion", nullptr, TestSetDrawRegion, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestSetMarkNodeGroup", nullptr, TestSetMarkNodeGroup, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestShadowAlpha", nullptr, TestShadowAlpha, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestShadowColor", nullptr, TestShadowColor, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestShadowElevation", nullptr, TestShadowElevation, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestShadowOffset", nullptr, TestShadowOffset, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestShadowRadius", nullptr, TestShadowRadius, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestSize", nullptr, TestSize, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestTransform", nullptr, TestTransform, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestTranslation", nullptr, TestTranslation, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestAddRenderNode001", nullptr, TestAddRenderNode001, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestAddRenderNode002", nullptr, TestAddRenderNode002, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestAddRenderNode003", nullptr, TestAddRenderNode003, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"TestRemoveRenderNode001", nullptr, TestRemoveRenderNode001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRemoveRenderNode002", nullptr, TestRemoveRenderNode002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestClearRenderNodeChildren001", nullptr, TestClearRenderNodeChildren001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestClearRenderNodeChildren002", nullptr, TestClearRenderNodeChildren002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestInvalidate", nullptr, TestInvalidate, nullptr, nullptr, nullptr, napi_default, nullptr},
            {"RenderNodeErrorCode001", nullptr, RenderNodeErrorCode001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode002", nullptr, RenderNodeErrorCode002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode003", nullptr, RenderNodeErrorCode003, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode004", nullptr, RenderNodeErrorCode004, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode005", nullptr, RenderNodeErrorCode005, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode006", nullptr, RenderNodeErrorCode006, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode007", nullptr, RenderNodeErrorCode007, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode008", nullptr, RenderNodeErrorCode008, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode009", nullptr, RenderNodeErrorCode009, nullptr, nullptr, nullptr,
                napi_default, nullptr},      
            {"RenderNodeErrorCode010", nullptr, RenderNodeErrorCode010, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode011", nullptr, RenderNodeErrorCode011, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode012", nullptr, RenderNodeErrorCode012, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode013", nullptr, RenderNodeErrorCode013, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode014", nullptr, RenderNodeErrorCode014, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode015", nullptr, RenderNodeErrorCode015, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode016", nullptr, RenderNodeErrorCode016, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode017", nullptr, RenderNodeErrorCode017, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode018", nullptr, RenderNodeErrorCode018, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode019", nullptr, RenderNodeErrorCode019, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode020", nullptr, RenderNodeErrorCode020, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode021", nullptr, RenderNodeErrorCode021, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode022", nullptr, RenderNodeErrorCode022, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode023", nullptr, RenderNodeErrorCode023, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode024", nullptr, RenderNodeErrorCode024, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode025", nullptr, RenderNodeErrorCode025, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode026", nullptr, RenderNodeErrorCode026, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode027", nullptr, RenderNodeErrorCode027, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode028", nullptr, RenderNodeErrorCode028, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode029", nullptr, RenderNodeErrorCode029, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode030", nullptr, RenderNodeErrorCode030, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode031", nullptr, RenderNodeErrorCode031, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode032", nullptr, RenderNodeErrorCode032, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode033", nullptr, RenderNodeErrorCode033, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode034", nullptr, RenderNodeErrorCode034, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode035", nullptr, RenderNodeErrorCode035, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode036", nullptr, RenderNodeErrorCode036, nullptr, nullptr, nullptr,
                napi_default, nullptr},       
            {"RenderNodeErrorCode037", nullptr, RenderNodeErrorCode037, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode038", nullptr, RenderNodeErrorCode038, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode039", nullptr, RenderNodeErrorCode039, nullptr, nullptr, nullptr,
                napi_default, nullptr},  
            {"RenderNodeErrorCode040", nullptr, RenderNodeErrorCode040, nullptr, nullptr, nullptr,
                napi_default, nullptr},  
            {"RenderNodeErrorCode041", nullptr, RenderNodeErrorCode041, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode042", nullptr, RenderNodeErrorCode042, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode043", nullptr, RenderNodeErrorCode043, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode044", nullptr, RenderNodeErrorCode044, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode045", nullptr, RenderNodeErrorCode045, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode046", nullptr, RenderNodeErrorCode046, nullptr, nullptr, nullptr,
                napi_default, nullptr},  
            {"RenderNodeErrorCode047", nullptr, RenderNodeErrorCode047, nullptr, nullptr, nullptr,
                napi_default, nullptr},  
            {"RenderNodeErrorCode048", nullptr, RenderNodeErrorCode048, nullptr, nullptr, nullptr,
                napi_default, nullptr}, 
            {"RenderNodeErrorCode049", nullptr, RenderNodeErrorCode049, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode050", nullptr, RenderNodeErrorCode050, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode051", nullptr, RenderNodeErrorCode051, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode052", nullptr, RenderNodeErrorCode052, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode053", nullptr, RenderNodeErrorCode053, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode054", nullptr, RenderNodeErrorCode054, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode055", nullptr, RenderNodeErrorCode055, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeErrorCode060", nullptr, RenderNodeErrorCode060, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeNullTest001", nullptr, RenderNodeNullTest001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeNullTest002", nullptr, RenderNodeNullTest002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode001", nullptr, TestRenderNode001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode009", nullptr, TestRenderNode009, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode002", nullptr, TestRenderNode002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode003", nullptr, TestRenderNode003, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode004", nullptr, TestRenderNode004, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode005", nullptr, TestRenderNode005, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode006", nullptr, TestRenderNode006, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode007", nullptr, TestRenderNode007, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"TestRenderNode008", nullptr, TestRenderNode008, nullptr, nullptr, nullptr,
                napi_default, nullptr},
			{"RenderNodeUtils_001", nullptr, RenderNodeUtils_001, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_002", nullptr, RenderNodeUtils_002, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_003", nullptr, RenderNodeUtils_003, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_004", nullptr, RenderNodeUtils_004, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_005", nullptr, RenderNodeUtils_005, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_006", nullptr, RenderNodeUtils_006, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_007", nullptr, RenderNodeUtils_007, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_008", nullptr, RenderNodeUtils_008, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_009", nullptr, RenderNodeUtils_009, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_010", nullptr, RenderNodeUtils_010, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_011", nullptr, RenderNodeUtils_011, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_012", nullptr, RenderNodeUtils_012, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_013", nullptr, RenderNodeUtils_013, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_014", nullptr, RenderNodeUtils_014, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_015", nullptr, RenderNodeUtils_015, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeUtils_016", nullptr, RenderNodeUtils_016, nullptr, nullptr, nullptr, 
                napi_default, nullptr},
            {"RenderNodeParam001", nullptr, RenderNodeParam001, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam002", nullptr, RenderNodeParam002, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam003", nullptr, RenderNodeParam003, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam004", nullptr, RenderNodeParam004, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam005", nullptr, RenderNodeParam005, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam006", nullptr, RenderNodeParam006, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam007", nullptr, RenderNodeParam007, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam008", nullptr, RenderNodeParam008, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam009", nullptr, RenderNodeParam009, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam010", nullptr, RenderNodeParam010, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam011", nullptr, RenderNodeParam011, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam012", nullptr, RenderNodeParam012, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam013", nullptr, RenderNodeParam013, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam014", nullptr, RenderNodeParam014, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam015", nullptr, RenderNodeParam015, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam016", nullptr, RenderNodeParam016, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam017", nullptr, RenderNodeParam017, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam018", nullptr, RenderNodeParam018, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam019", nullptr, RenderNodeParam019, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam020", nullptr, RenderNodeParam020, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam021", nullptr, RenderNodeParam021, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam022", nullptr, RenderNodeParam022, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam023", nullptr, RenderNodeParam023, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam024", nullptr, RenderNodeParam024, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam025", nullptr, RenderNodeParam025, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam026", nullptr, RenderNodeParam026, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam027", nullptr, RenderNodeParam027, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam028", nullptr, RenderNodeParam028, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam029", nullptr, RenderNodeParam029, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam030", nullptr, RenderNodeParam030, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam031", nullptr, RenderNodeParam031, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam032", nullptr, RenderNodeParam032, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam033", nullptr, RenderNodeParam033, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam034", nullptr, RenderNodeParam034, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam035", nullptr, RenderNodeParam035, nullptr, nullptr, nullptr,
                napi_default, nullptr},
            {"RenderNodeParam036", nullptr, RenderNodeParam036, nullptr, nullptr, nullptr,
                napi_default, nullptr},
        };
        if (napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc) != napi_ok)
        {
            OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_PRINT_DOMAIN, "Init", "napi_define_properties failed");
            return nullptr;
        }
        return exports;
    }
    EXTERN_C_END

    static napi_module nativefuncModule = {.nm_version = 1,
                                           .nm_flags = 0,
                                           .nm_filename = nullptr,
                                           .nm_register_func = Init,
                                           .nm_modname = "nativefunc",
                                           .nm_priv = ((void *)0),
                                           .reserved = {0}};

    extern "C" __attribute__((constructor)) void RegisterModule(void) { napi_module_register(&nativefuncModule); }
} // namespace ArkUICapiTest
