/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <string>
#include <sys/wait.h>
#include <unistd.h>
#include <unordered_map>
#include "CommonTool.h"
#include "libc_generated_100.h"
#include "libc_generated_extra.h"
#include "libc_test_cases.h"
#include "malloc-pressure.h"
#include "napi/native_api.h"
#include "src/eabi.h"
#include "src/functional.h"
#include "src/functionalext/dl_different_hash.h"
#include "src/functionalext/dlns.h"
#include "src/functionalext/info.h"
#include "src/functionalext/ldso_cfi.h"
#include "src/functionalext/ldso_cfi/crossdso.h"
#include "src/functionalext/ldso_cfi/crossdso_dtor.h"
#include "src/functionalext/locale.h"
#include "src/functionalext/relro.h"
#include "src/functionalext/supplement/ctype.h"
#include "src/functionalext/supplement/dirent.h"
#include "src/functionalext/supplement/errno.h"
#include "src/functionalext/supplement/exit.h"
#include "src/functionalext/supplement/fcntl.h"
#include "src/functionalext/supplement/ldso.h"
#include "src/functionalext/supplement/legacy.h"
#include "src/functionalext/supplement/linux.h"
#include "src/functionalext/supplement/locale.h"
#include "src/functionalext/supplement/malloc.h"
#include "src/functionalext/supplement/manual/env.h"
#include "src/functionalext/supplement/math.h"
#include "src/functionalext/supplement/misc.h"
#include "src/functionalext/supplement/multibyte.h"
#include "src/functionalext/supplement/network.h"
#include "src/functionalext/supplement/prng.h"
#include "src/functionalext/supplement/process.h"
#include "src/functionalext/supplement/sched.h"
#include "src/functionalext/supplement/setjmp.h"
#include "src/functionalext/supplement/signal.h"
#include "src/functionalext/supplement/stat.h"
#include "src/functionalext/supplement/stdio.h"
#include "src/functionalext/supplement/stdlib.h"
#include "src/functionalext/supplement/string.h"
#include "src/functionalext/supplement/termios.h"
#include "src/functionalext/supplement/thread.h"
#include "src/functionalext/supplement/time.h"
#include "src/functionalext/supplement/unistd.h"
#include "src/functionalext/symver.h"
#include "src/functionalext/time.h"
#include "src/math.h"
#include "src/regression.h"
#include "test.h"
#include "src/functionalext/supplement/ipc.h"
#include "src/functionalext/supplement/lock_info.h"
#include "src/functionalext/supplement/manual/network.h"
#include "src/functionalext/supplement/search.h"
#include "src/functionalext/unittest.h"

namespace {
constexpr int K_RUN_TEST_NOT_FOUND = 404;
constexpr int K_RUN_TEST_FORK_FAILED = 500;
constexpr int K_RUN_TEST_WAITPID_FAILED = 501;
constexpr int K_RUN_TEST_UNKNOWN_EXIT = 502;
constexpr int K_CHILD_EXIT_CAP = 255;
constexpr int K_SIGNAL_EXIT_BASE = 128;
} // namespace

namespace {
const std::unordered_map<std::string, int (*)()> kTestRegistry = {
    { "basename", &BasenameTest },
    { "dirname", &DirnameTest },
    { "env", &EnvTest },
    { "iswspace-null", &IswspaceNullTest },
    { "wcsncpy-read-overflow", &WcsncpyReadOverflowTest },
    { "memmem-oob", &MemmemOobTest },
    { "strtod_long", &StrtodLongTest },
    { "getpwnam_r-crash", &GetpwnamRCrashTest },
    { "putenv-doublefree", &PutenvDoublefreeTest },
    { "sigreturn", &SigreturnTest },
    { "main", &MainTest },
    { "fnmatch", &FnmatchTest },
    { "iconv", &IconvTest },
    { "tgkill", &TgkillTest },
    { "poll", &PollTest },
    { "lrand48-signextend", &Lrand48SignextendTest },
    { "scanf-nullbyte-char", &ScanfNullbyteCharTest },
    { "scanf-match-literal-eof", &ScanfMatchLiteralEofTest },
    { "setvbuf-unget", &SetvbufUngetTest },
    { "clock_gettime", &ClockGettimeTest },
    { "memmem-oob-read", &MemmemOobReadTest },
    { "getpwnam_r-errno", &GetpwnamRErrnoTest },
    { "regexec-nosub", &RegexecNosubTest },
    { "dn_expand-empty", &DnExpandEmptyTest },
    { "scanf-bytes-consumed", &ScanfBytesConsumedTest },
    { "wcsstr-false-negative", &WcsstrFalseNegativeTest },
    { "fgets-eof", &FgetsEofTest },
    { "sscanf-eof", &SscanfEofTest },
    { "regex-escaped-high-byte", &RegexEscapedHighByteTest },
    { "regex-negated-range", &RegexNegatedRangeTest },
    { "malloc-0", &Malloc0Test },
    { "malloc-pressure", &MallocPressureTest },
    { "regex-backref-0", &RegexBackref0Test },
    { "printf-fmt-g-round", &PrintfFmtGRoundTest },
    { "printf-fmt-g-zeros", &PrintfFmtGZerosTest },
    { "sched_cpualloc", &SchedCpuallocTest },
    { "inet_ntop-v4mapped", &InetNtopV4mappedTest },
    { "setjmp", &SetjmpTest },
    { "mbsrtowcs-overflow", &MbsrtowcsOverflowTest },
    { "rewind-clear-error", &RewindClearErrorTest },
    { "syscall-sign-extend", &SyscallSignExtendTest },
    { "string_strcspn", &StringStrcspnTest },
    { "uselocale-0", &Uselocale0Test },
    { "printf-1e9-oob", &Printf1e9OobTest },
    { "strtod_simple", &StrtodSimpleTest },
    { "pthread_gettid_np", &PthreadGettidNpTest },
    { "search_insque", &SearchInsqueTest },
    { "mkstemp-failure", &MkstempFailureTest },
    { "printf-fmt-n", &PrintfFmtNTest },
    { "regex-ere-backref", &RegexEreBackrefTest },
    { "pthread_exit-cancel", &PthreadExitCancelTest },
    { "sched_setscheduler", &SchedSetschedulerTest },
    { "langinfo", &LanginfoTest },
    { "strverscmp", &StrverscmpTest },
    { "fgetwc-buffering", &FgetwcBufferingTest },
    { "mkdtemp-failure", &MkdtempFailureTest },
    { "sscanf_long", &SscanfLongTest },
    { "tls_init", &TlsInitTest },
    { "sigprocmask-internal", &SigprocmaskInternalTest },
    { "regex-bracket-icase", &RegexBracketIcaseTest },
    { "dn_expand-ptr-0", &DnExpandPtr0Test },
    { "search_lsearch", &SearchLsearchTest },
    { "rlimit-open-files", &RlimitOpenFilesTest },
    { "inet_pton-empty-last-field", &InetPtonEmptyLastFieldTest },
    { "setpriority", &SetpriorityTest },
    { "vwarn", &VwarnTest },
    { "get_phys_pages", &GetPhysPagesTest },
    { "setpgrp", &SetpgrpTest },
    { "vwarnx", &VwarnxTest },
    { "get_avphys_pages", &GetAvphysPagesTest },
    { "issetugid", &IssetugidTest },
    { "atexit", &AtexitTest },
    { "atexit_dlclose", &AtexitDlcloseTest },
    { "dlclose_reset", &DlcloseResetTest },
    { "verr", &VerrTest },
    { "__h_errno_location", &HErrnoLocationTest },
    { "__recvmmsg_time64", &RecvmmsgTime64Test },
    { "readahead", &ReadaheadTest },
    { "verrx", &VerrxTest },
    { "getdtablesize", &GetdtablesizeTest },
    { "get_nprocs", &GetNprocsTest },
    { "__flt_rounds", &FltRoundsTest },
    { "gethostname", &GethostnameTest },
    { "sigpending", &SigpendingTest },
    { "sched_getcpu", &SchedGetcpuTest },
    { "supplementSetjmp", &SupplementSetjmpTest },
    { "ftw", &FtwTest },
    { "__gmtime64", &Gmtime64Test },
    { "wcsftime", &WcsftimeTest },
    { "string_memcpy", &StringMemcpyTest },
    { "device_api_version", &DeviceApiVersionTest },
    { "__aeabi_memclr", &AeabiMemclrTest },
    { "__aeabi_memcpy", &AeabiMemcpyTest },
    { "__aeabi_memmove", &AeabiMemmoveTest },
    { "__aeabi_read_tp", &AeabiReadTpTest },
    { "__ctype_get_mb_cur_max", &CtypeGetMbCurMaxTest },
    { "__fbufsize", &FbufsizeTest },
    { "__flbf", &FlbfTest },
    { "__fpclassifyf", &FpclassifyfTest },
    { "__fpclassifyl", &FpclassifylTest },
    { "__libc_current_sigrtmax", &LibcCurrentSigrtmaxTest },
    { "__libc_current_sigrtmin", &LibcCurrentSigrtminTest },
    { "__sched_cpucount", &SchedCpucountTest },
    { "__signbitf", &SignbitfTest },
    { "__signbitl", &SignbitlTest },
    { "__sigtimedwait_time64", &SigtimedwaitTime64Test },
    { "_longjmp", &LongjmpTest },
    { "abs", &AbsTest },
    { "acos", &AcosTest },
    { "acosh", &AcoshTest },
    { "acoshf", &AcoshfTest },
    { "acosl", &AcoslTest },
    { "alarm", &AlarmTest },
    { "aligned_alloc", &AlignedAllocTest },
    { "application_target_sdk_version_test", &ApplicationTargetSdkVersionTestTest },
    { "argv", &ArgvTest },
    { "asin", &AsinTest },
    { "asinf", &AsinfTest },
    { "asinh", &AsinhTest },
    { "asinhf", &AsinhfTest },
    { "asinl", &AsinlTest },
    { "at_quick_exit", &AtQuickExitTest },
    { "atan", &AtanTest },
    { "atan2", &Atan2Test },
    { "atan2f", &Atan2fTest },
    { "atan2l", &Atan2lTest },
    { "atanf", &AtanfTest },
    { "atanh", &AtanhTest },
    { "atanhf", &AtanhfTest },
    { "atanhl", &AtanhlTest },
    { "atanl", &AtanlTest },
    { "atof", &AtofTest },
    { "atoi", &AtoiTest },
    { "atoll", &AtollTest },
    { "brk", &BrkTest },
    { "bsearch", &BsearchTest },
    { "bzero", &BzeroTest },
    { "c16rtomb", &C16rtombTest },
    { "c32rtomb", &C32rtombTest },
    { "capget", &CapgetTest },
    { "cbrt", &CbrtTest },
    { "cbrtf", &CbrtfTest },
    { "cbrtl", &CbrtlTest },
    { "ceil", &CeilTest },
    { "ceilf", &CeilfTest },
    { "ceill", &CeillTest },
    { "cfgetispeed", &CfgetispeedTest },
    { "cfgetospeed", &CfgetospeedTest },
    { "cfmakeraw", &CfmakerawTest },
    { "cfsetispeed", &CfsetispeedTest },
    { "cfsetospeed", &CfsetospeedTest },
    { "chdir", &ChdirTest },
    { "clearerr", &ClearerrTest },
    { "clock", &ClockTest },
    { "clock_getcpuclockid", &ClockGetcpuclockidTest },
    { "clock_getres", &ClockGetresTest },
    { "gmtime_r_sup", &GmtimeRSupTest },
    { "gmtime_sup", &GmtimeSupTest },
    { "nanosleep", &NanosleepTest },
    { "timer_create", &TimerCreateTest },
    { "timer_getoverrun", &TimerGetoverrunTest },
    { "timer_gettime", &TimerGettimeTest },
    { "timer_settime", &TimerSettimeTest },
    { "timespec_get", &TimespecGetTest },
    { "utime_sup", &UtimeSupTest },
    { "clone", &CloneTest },
    { "cnd_init", &CndInitTest },
    { "cnd_signal", &CndSignalTest },
    { "copysign", &CopysignTest },
    { "copysignf", &CopysignfTest },
    { "copysignl", &CopysignlTest },
    { "cos", &CosTest },
    { "cosf", &CosfTest },
    { "cosh", &CoshTest },
    { "coshf", &CoshfTest },
    { "coshl", &CoshlTest },
    { "cosl", &CoslTest },
    { "crypt", &CryptTest },
    { "ctermid", &CtermidTest },
    { "ctime", &CtimeTest },
    { "ctime_r", &CtimeRTest },
    { "daemon-failure", &DaemonFailureTest },
    { "difftime_sup", &DifftimeSupTest },
    { "dn_comp", &DnCompTest },
    { "dn_skipname", &DnSkipnameTest },
    { "drand48", &Drand48Test },
    { "drem", &DremTest },
    { "dremf", &DremfTest },
    { "duplocale_sup", &DuplocaleSupTest },
    { "epoll_create", &EpollCreateTest },
    { "epoll_create1", &EpollCreate1Test },
    { "epoll_ctl", &EpollCtlTest },
    { "epoll_pwait", &EpollPwaitTest },
    { "epoll_wait", &EpollWaitTest },
    { "erand48", &Erand48Test },
    { "erf", &ErfTest },
    { "erfc", &ErfcTest },
    { "erfcf", &ErfcfTest },
    { "erff", &ErffTest },
    { "erfl", &ErflTest },
    { "eventfd", &EventfdTest },
    { "eventfd_read", &EventfdReadTest },
    { "eventfd_write", &EventfdWriteTest },
    { "flistxattr", &FlistxattrTest },
    { "fremovexattr", &FremovexattrTest },
    { "fsetxattr", &FsetxattrTest },
    { "getdents", &GetdentsTest },
    { "copy_file_range", &CopyFileRangeTest },
    { "name_to_handle_at", &NameToHandleAtTest },
    { "process_vm", &ProcessVmTest },
    { "remap_file_pages", &RemapFilePagesTest },
    { "removexattr", &RemovexattrTest },
    { "sbrk", &SbrkTest },
    { "setxattr", &SetxattrTest },
    { "swapoff", &SwapoffTest },
    { "swapon", &SwaponTest },
    { "tee", &TeeTest },
    { "timerfd_gettime", &TimerfdGettimeTest },
    { "timerfd_settime", &TimerfdSettimeTest },
    { "execl", &ExeclTest },
    { "exp", &ExpTest },
    { "exp2", &Exp2Test },
    { "exp2f", &Exp2fTest },
    { "exp2l", &Exp2lTest },
    { "expf", &ExpfTest },
    { "expl", &ExplTest },
    { "expm1", &Expm1Test },
    { "expm1f", &Expm1fTest },
    { "expm1l", &Expm1lTest },
    { "fabs", &FabsTest },
    { "fabsf", &FabsfTest },
    { "fabsl", &FabslTest },
    { "fanotify_init", &FanotifyInitTest },
    { "fdiml", &FdimlTest },
    { "feholdexcept", &FeholdexceptTest },
    { "fexecve", &FexecveTest },
    { "fexecverely", &FexecverelyTest },
    { "fork", &ForkTest },
    { "fflush", &FflushTest },
    { "ffs", &FfsTest },
    { "ffsl", &FfslTest },
    { "ffsll", &FfsllTest },
    { "finitef", &FinitefTest },
    { "floor", &FloorTest },
    { "floorf", &FloorfTest },
    { "floorl", &FloorlTest },
    { "fmax", &FmaxTest },
    { "fmaxf", &FmaxfTest },
    { "fmaxl", &FmaxlTest },
    { "fpathconf", &FpathconfTest },
    { "freeaddrinfo", &FreeaddrinfoTest },
    { "freeifaddrs", &FreeifaddrsTest },
    { "frexp", &FrexpTest },
    { "frexpf", &FrexpfTest },
    { "frexpl", &FrexplTest },
    { "gai_strerror", &GaiStrerrorTest },
    { "getauxval", &GetauxvalTest },
    { "getcwd", &GetcwdTest },
    { "getdomainname", &GetdomainnameTest },
    { "getentropy", &GetentropyTest },
    { "getgrent", &GetgrentTest },
    { "getgrgid", &GetgrgidTest },
    { "getgrgid_r", &GetgrgidRTest },
    { "getgrnam", &GetgrnamTest },
    { "getgrnam_r", &GetgrnamRTest },
    { "getgrouplist", &GetgrouplistTest },
    { "getgroups", &GetgroupsTest },
    { "gethostbyaddr", &GethostbyaddrTest },
    { "gethostbyaddr_r", &GethostbyaddrRTest },
    { "gethostbyname2_r", &Gethostbyname2RTest },
    { "gethostent", &GethostentTest },
    { "getifaddrs", &GetifaddrsTest },
    { "getitimer", &GetitimerTest },
    { "__getitimer_time64", &GetitimerTime64Test },
    { "__setitimer_time64", &SetitimerTime64Test },
    { "getloadavg", &GetloadavgTest },
    { "getlogin", &GetloginTest },
    { "getlogin_r", &GetloginRTest },
    { "getnameinfo", &GetnameinfoTest },
    { "getnetent", &GetnetentTest },
    { "getopt", &GetoptTest },
    { "getopt_long", &GetoptLongTest },
    { "getopt_long_only", &GetoptLongOnlyTest },
    { "getpgid", &GetpgidTest },
    { "getpgrp", &GetpgrpTest },
    { "getppid", &GetppidTest },
    { "getrandom", &GetrandomTest },
    { "getresuid", &GetresuidTest },
    { "getrlimit", &GetrlimitTest },
    { "getservbyname", &GetservbynameTest },
    { "getservbyport", &GetservbyportTest },
    { "getsid", &GetsidTest },
    { "getsubopt", &GetsuboptTest },
    { "hasmntopt", &HasmntoptTest },
    { "hcreate_r", &HcreateRTest },
    { "hdestroy", &HdestroyTest },
    { "hsearch_r", &HsearchRTest },
    { "hstrerror", &HstrerrorTest },
    { "htonl", &HtonlTest },
    { "htons", &HtonsTest },
    { "hypot", &HypotTest },
    { "hypotf", &HypotfTest },
    { "hypotl", &HypotlTest },
    { "iconv-roundtrips", &IconvRoundtripsTest },
    { "iconv_open", &IconvOpenTest },
    { "iconv_test", &IconvTestTest },
    { "iconv_joint_icu_test", &IconvJointIcuTestTest },
    { "if_indextoname", &IfIndextonameTest },
    { "if_nameindex", &IfNameindexTest },
    { "ilogb", &IlogbTest },
    { "ilogbf", &IlogbfTest },
    { "ilogbl", &IlogblTest },
    { "imaxabs", &ImaxabsTest },
    { "imaxdiv", &ImaxdivTest },
    { "index", &IndexTest },
    { "inet_addr", &InetAddrTest },
    { "inet_aton", &InetAtonTest },
    { "inet_lnaof", &InetLnaofTest },
    { "inet_makeaddr", &InetMakeaddrTest },
    { "inet_netof", &InetNetofTest },
    { "inet_network", &InetNetworkTest },
    { "inet_ntoa", &InetNtoaTest },
    { "inet_ntop", &InetNtopTest },
    { "inotify_init1", &InotifyInit1Test },
    { "res_mkquery", &ResMkqueryTest },
    { "res_query", &ResQueryTest },
    { "res_querydomain", &ResQuerydomainTest },
    { "sendmmsg", &SendmmsgTest },
    { "invalid_param_b", &InvalidParamBTest },
    { "isalnum", &IsalnumTest },
    { "isalpha", &IsalphaTest },
    { "isascii", &IsasciiTest },
    { "isblank", &IsblankTest },
    { "iscntrl", &IscntrlTest },
    { "isdigit", &IsdigitTest },
    { "isgraph", &IsgraphTest },
    { "isless", &IslessTest },
    { "islower", &IslowerTest },
    { "isprint", &IsprintTest },
    { "ispunct", &IspunctTest },
    { "isspace", &IsspaceTest },
    { "isupper", &IsupperTest },
    { "iswalhpa", &IswalhpaTest },
    { "iswalnum", &IswalnumTest },
    { "iswctype", &IswctypeTest },
    { "iswctype_l", &IswctypeLTest },
    { "iswgraph", &IswgraphTest },
    { "isxdigit", &IsxdigitTest },
    { "kill", &KillTest },
    { "killpg", &KillpgTest },
    { "labs", &LabsTest },
    { "langinfo_sup", &LanginfoSupTest },
    { "large_size_test", &LargeSizeTestTest },
    { "ldso_dlopen_config_abs_path_1", &LdsoDlopenConfigAbsPath1Test },
    { "ldso_dlopen_config_abs_path_10", &LdsoDlopenConfigAbsPath10Test },
    { "ldso_dlopen_config_abs_path_11", &LdsoDlopenConfigAbsPath11Test },
    { "ldso_dlopen_config_abs_path_12", &LdsoDlopenConfigAbsPath12Test },
    { "ldso_dlopen_config_abs_path_13", &LdsoDlopenConfigAbsPath13Test },
    { "ldso_dlopen_config_abs_path_14", &LdsoDlopenConfigAbsPath14Test },
    { "ldso_dlopen_config_abs_path_15", &LdsoDlopenConfigAbsPath15Test },
    { "ldso_dlopen_config_abs_path_16", &LdsoDlopenConfigAbsPath16Test },
    { "ldso_dlopen_config_abs_path_2", &LdsoDlopenConfigAbsPath2Test },
    { "ldso_dlopen_config_abs_path_3", &LdsoDlopenConfigAbsPath3Test },
    { "ldso_dlopen_config_abs_path_4", &LdsoDlopenConfigAbsPath4Test },
    { "ldso_dlopen_config_abs_path_5", &LdsoDlopenConfigAbsPath5Test },
    { "ldso_dlopen_config_abs_path_6", &LdsoDlopenConfigAbsPath6Test },
    { "ldso_dlopen_config_abs_path_7", &LdsoDlopenConfigAbsPath7Test },
    { "ldso_dlopen_config_abs_path_8", &LdsoDlopenConfigAbsPath8Test },
    { "ldso_dlopen_config_abs_path_9", &LdsoDlopenConfigAbsPath9Test },
    { "lcong48", &Lcong48Test },
    { "ldiv", &LdivTest },
    { "link", &LinkTest },
    { "llabs", &LlabsTest },
    { "lldiv", &LldivTest },
    { "localeconv", &LocaleconvTest },
    { "localeconv_multithread", &LocaleconvMultithreadTest },
    { "login_tty", &LoginTtyTest },
    { "lrand48", &Lrand48Test },
    { "malloc-free-performance", &MallocFreePerformanceTest },
    { "malloc-multi-thread-performance", &MallocMultiThreadPerformanceTest },
    { "malloc_check_from_ptr", &MallocCheckFromPtrTest },
    { "malloc_usable_size", &MallocUsableSizeTest },
    { "mbc", &MbcTest },
    { "mblen", &MblenTest },
    { "mbrlen", &MbrlenTest },
    { "mbrtoc16", &Mbrtoc16Test },
    { "mbrtoc32", &Mbrtoc32Test },
    { "mbsinit", &MbsinitTest },
    { "mbsnrtowcs", &MbsnrtowcsTest },
    { "mbstowcs", &MbstowcsTest },
    { "mbtowc", &MbtowcTest },
    { "memalign", &MemalignTest },
    { "memccpy", &MemccpyTest },
    { "memchr", &MemchrTest },
    { "memfd_create", &MemfdCreateTest },
    { "memmove", &MemmoveTest },
    { "mempcpy", &MempcpyTest },
    { "mktemp", &MktempTest },
    { "mkostemp", &MkostempTest },
    { "mkostemps", &MkostempsTest },
    { "mkstemp", &MkstempTest },
    { "mkstemps", &MkstempsTest },
    { "mktime_sup", &MktimeSupTest },
    { "mlock", &MlockTest },
    { "mlock2", &Mlock2Test },
    { "mprotect", &MprotectTest },
    { "mrand48", &Mrand48Test },
    { "mtx_init", &MtxInitTest },
    { "mtx_lock", &MtxLockTest },
    { "munlock", &MunlockTest },
    { "nan", &NanTest },
    { "nanf", &NanfTest },
    { "nanl", &NanlTest },
    { "nativehook_test", &NativehookTestTest },
    { "newlocale", &NewlocaleTest },
    { "ohos_dfx_log", &OhosDfxLogTest },
    { "open_wmemstream", &OpenWmemstreamTest },
    { "pathconf", &PathconfTest },
    { "pause", &PauseTest },
    { "personality", &PersonalityTest },
    { "pipe2", &Pipe2Test },
    { "posix_memalign", &PosixMemalignTest },
    { "posix_spawn", &PosixSpawnTest },
    { "posix_spawnattr_getflags", &PosixSpawnattrGetflagsTest },
    { "posix_spawnattr_getpgroup", &PosixSpawnattrGetpgroupTest },
    { "posix_spawnattr_getsigdefault", &PosixSpawnattrGetsigdefaultTest },
    { "posix_spawnattr_getsigmask", &PosixSpawnattrGetsigmaskTest },
    { "posix_spawnattr_setflags", &PosixSpawnattrSetflagsTest },
    { "posix_spawnattr_setpgroup", &PosixSpawnattrSetpgroupTest },
    { "posix_spawnattr_setsigdefault", &PosixSpawnattrSetsigdefaultTest },
    { "posix_spawnattr_setsigmask", &PosixSpawnattrSetsigmaskTest },
    { "posix_spawnp", &PosixSpawnpTest },
    { "prctl", &PrctlTest },
    { "printf", &PrintfTest },
    { "prlimit", &PrlimitTest },
    { "proto", &ProtoTest },
    { "pselect", &PselectTest },
    { "psiginfo", &PsiginfoTest },
    { "psignal", &PsignalTest },
    { "pthread_atfork", &PthreadAtforkTest },
    { "pthread_attr_destroy", &PthreadAttrDestroyTest },
    { "pthread_attr_get", &PthreadAttrGetTest },
    { "pthread_attr_getstack_test", &PthreadAttrGetstackTestTest },
    { "pthread_attr_init", &PthreadAttrInitTest },
    { "pthread_attr_setguardsize", &PthreadAttrSetguardsizeTest },
    { "pthread_attr_setinheritsched", &PthreadAttrSetinheritschedTest },
    { "pthread_attr_setschedparam", &PthreadAttrSetschedparamTest },
    { "pthread_attr_setschedpolicy", &PthreadAttrSetschedpolicyTest },
    { "pthread_attr_setscope", &PthreadAttrSetscopeTest },
    { "pthread_attr_setstack", &PthreadAttrSetstackTest },
    { "pthread_attr_setstacksize_test", &PthreadAttrSetstacksizeTestTest },
    { "pthread_barrier_destroy", &PthreadBarrierDestroyTest },
    { "pthread_barrier_init", &PthreadBarrierInitTest },
    { "pthread_barrierattr_init", &PthreadBarrierattrInitTest },
    { "pthread_barrierattr_setpshared", &PthreadBarrierattrSetpsharedTest },
    { "pthread_cond_broadcast", &PthreadCondBroadcastTest },
    { "pthread_cond_destroy", &PthreadCondDestroyTest },
    { "pthread_cond_signal", &PthreadCondSignalTest },
    { "pthread_cond_wait", &PthreadCondWaitTest },
    { "pthread_condattr_destroy_test", &PthreadCondattrDestroyTestTest },
    { "pthread_condattr_init_test", &PthreadCondattrInitTestTest },
    { "pthread_condattr_setclock", &PthreadCondattrSetclockTest },
    { "pthread_condattr_setclock_sup", &PthreadCondattrSetclockSupTest },
    { "pthread_condattr_setpshared", &PthreadCondattrSetpsharedTest },
    { "pthread_getcpuclockid", &PthreadGetcpuclockidTest },
    { "pthread_getname_np", &PthreadGetnameNpTest },
    { "pthread_key_delete", &PthreadKeyDeleteTest },
    { "pthread_mutex_destroy", &PthreadMutexDestroyTest },
    { "pthread_mutex_init_test", &PthreadMutexInitTestTest },
    { "pthread_mutex_trylock", &PthreadMutexTrylockTest },
    { "pthread_mutexattr_destroy", &PthreadMutexattrDestroyTest },
    { "pthread_mutexattr_setprotocol", &PthreadMutexattrSetprotocolTest },
    { "pthread_mutexattr_setpshared", &PthreadMutexattrSetpsharedTest },
    { "pthread_mutexattr_settype", &PthreadMutexattrSettypeTest },
    { "pthread_rwlock_destroy_test", &PthreadRwlockDestroyTestTest },
    { "pthread_rwlock_rdlock_sup", &PthreadRwlockRdlockSupTest },
    { "pthread_rwlock_tryrdlock", &PthreadRwlockTryrdlockTest },
    { "pthread_rwlock_trywrlock", &PthreadRwlockTrywrlockTest },
    { "pthread_rwlockattr_destroy", &PthreadRwlockattrDestroyTest },
    { "pthread_rwlockattr_init", &PthreadRwlockattrInitTest },
    { "pthread_rwlockattr_setpshared", &PthreadRwlockattrSetpsharedTest },
    { "pthread_sigmask_test", &PthreadSigmaskTestTest },
    { "ptsname", &PtsnameTest },
    { "putc_unlocked", &PutcUnlockedTest },
    { "putchar", &PutcharTest },
    { "putchar_unlocked", &PutcharUnlockedTest },
    { "putenv", &PutenvTest },
    { "puts", &PutsTest },
    { "putwchar", &PutwcharTest },
    { "quick_exit", &QuickExitTest },
    { "quotactl", &QuotactlTest },
    { "raise-race", &RaiseRaceTest },
    { "rand", &RandTest },
    { "rand_r", &RandRTest },
    { "readdir", &ReaddirTest },
    { "realloc", &ReallocTest },
    { "realpath", &RealpathTest },
    { "regexec", &RegexecTest },
    { "rint_ext", &RintExtTest },
    { "sched_getaffinity", &SchedGetaffinityTest },
    { "sched_getparam", &SchedGetparamTest },
    { "sched_rr_get_interval", &SchedRrGetIntervalTest },
    { "sched_scheduler", &SchedSchedulerTest },
    { "sched_setaffinity", &SchedSetaffinityTest },
    { "sched_yield", &SchedYieldTest },
    { "search_hsearch", &SearchHsearchTest },
    { "seed48", &Seed48Test },
    { "sendmsg", &SendmsgTest },
    { "setfsgid", &SetfsgidTest },
    { "setfsuid", &SetfsuidTest },
    { "setgrent", &SetgrentTest },
    { "setlocale", &SetlocaleTest },
    { "setlogmask", &SetlogmaskTest },
    { "setprotoent", &SetprotoentTest },
    { "setpwent", &SetpwentTest },
    { "setsid", &SetsidTest },
    { "sigaction", &SigactionTest },
    { "sigaltstack", &SigaltstackTest },
    { "sigignore", &SigignoreTest },
    { "signalfd", &SignalfdTest },
    { "significand", &SignificandTest },
    { "significandf", &SignificandfTest },
    { "sigqueue", &SigqueueTest },
    { "sighold", &SigholdTest },
    { "sigpause", &SigpauseTest },
    { "sigrelse", &SigrelseTest },
    { "sigset", &SigsetTest },
    { "sigsuspend", &SigsuspendTest },
    { "sigwait", &SigwaitTest },
    { "sigwaitinfo", &SigwaitinfoTest },
    { "sleep", &SleepTest },
    { "socketpair", &SocketpairTest },
    { "sprintf", &SprintfTest },
    { "srand", &SrandTest },
    { "srand48", &Srand48Test },
    { "strcasecmp", &StrcasecmpTest },
    { "strcasestr", &StrcasestrTest },
    { "strcat", &StrcatTest },
    { "strchrnul", &StrchrnulTest },
    { "strcoll", &StrcollTest },
    { "strdup", &StrdupTest },
    { "strerror", &StrerrorTest },
    { "strerror_r", &StrerrorRTest },
    { "strftime", &StrftimeTest },
    { "string_strstr", &StringStrstrTest },
    { "strlen_test", &StrlenTestTest },
    { "reloc_symver", &RelocSymverTest },
    { "dlsym", &DlsymTest },
    { "dlvsym", &DlvsymTest },
    { "dynlink", &DynlinkTest },
    { "strndup", &StrndupTest },
    { "strnlen", &StrnlenTest },
    { "strptime", &StrptimeTest },
    { "strsep", &StrsepTest },
    { "strsignal", &StrsignalTest },
    { "strtod_l", &StrtodLTest },
    { "strtoimax", &StrtoimaxTest },
    { "strtol", &StrtolTest },
    { "strtold", &StrtoldTest },
    { "strtoumax", &StrtoumaxTest },
    { "swscanf", &SwscanfTest },
    { "sys_queue", &SysQueueTest },
    { "sysconf", &SysconfTest },
    { "sysinfo", &SysinfoTest },
    { "tempnam", &TempnamTest },
    { "thrd_yield", &ThrdYieldTest },
    { "timer_delete", &TimerDeleteTest },
    { "timerfd_create", &TimerfdCreateTest },
    { "times", &TimesTest },
    { "tmpnam", &TmpnamTest },
    { "toascii", &ToasciiTest },
    { "towctrans", &TowctransTest },
    { "tss_set", &TssSetTest },
    { "udiv", &UdivTest },
    { "umask", &UmaskTest },
    { "uname", &UnameTest },
    { "unittest_backtrace", &UnittestBacktraceTest },
    { "dl_different_hash_exe", &DlDifferentHashExeTest },
    { "unittest_fatal_message_assert_fail", &UnittestFatalMessageAssertFailTest },
    { "uselocale", &UselocaleTest },
    { "usleep", &UsleepTest },
    { "vasprintf", &VasprintfTest },
    { "vmsplice", &VmspliceTest },
    { "vprintf", &VprintfTest },
    { "vsnprintf", &VsnprintfTest },
    { "vsprintf", &VsprintfTest },
    { "vsscanf", &VsscanfTest },
    { "vswprintf", &VswprintfTest },
    { "vswscanf", &VswscanfTest },
    { "vwprintf", &VwprintfTest },
    { "waitid", &WaitidTest },
    { "wcpcpy", &WcpcpyTest },
    { "wcscasecmp", &WcscasecmpTest },
    { "wcscasecmp_l", &WcscasecmpLTest },
    { "wcschr", &WcschrTest },
    { "wcscmp", &WcscmpTest },
    { "wcscoll", &WcscollTest },
    { "wcscspn", &WcscspnTest },
    { "wcsftime_l", &WcsftimeLTest },
    { "wcslen", &WcslenTest },
    { "wcsncasecmp", &WcsncasecmpTest },
    { "wcsncasecmp_l", &WcsncasecmpLTest },
    { "wcsncat", &WcsncatTest },
    { "wcsncmp", &WcsncmpTest },
    { "wcsnlen", &WcsnlenTest },
    { "wcsrchr", &WcsrchrTest },
    { "wcsrtombs", &WcsrtombsTest },
    { "wcsspn", &WcsspnTest },
    { "wcsstr", &WcsstrTest },
    { "wcstod", &WcstodTest },
    { "wcstod_l", &WcstodLTest },
    { "wcstof", &WcstofTest },
    { "wcstok", &WcstokTest },
    { "wcstol", &WcstolTest },
    { "wcstold", &WcstoldTest },
    { "wcstoll", &WcstollTest },
    { "wcstombs", &WcstombsTest },
    { "wcstoull", &WcstoullTest },
    { "wcswcs", &WcswcsTest },
    { "wcswidth", &WcswidthTest },
    { "wcsxfrm", &WcsxfrmTest },
    { "wctob", &WctobTest },
    { "wctomb", &WctombTest },
    { "wctrans", &WctransTest },
    { "wctype", &WctypeTest },
    { "wcwidth", &WcwidthTest },
    { "write", &WriteTest },
    { "writev", &WritevTest },
    { "wcwidth", &WcwidthTest },
    { "wmemchr", &WmemchrTest },
    { "wmemcmp", &WmemcmpTest },
    { "wmemcpy", &WmemcpyTest },
    { "wmemmove", &WmemmoveTest },
    { "wmemset", &WmemsetTest },
    { "wprintf", &WprintfTest },
    { "writev", &WritevTest },
    { "malloc-oom", &MallocOomTest },
    { "setenv-oom", &SetenvOomTestCompat },
    { "pthread_create-oom", &PthreadCreateOomTest },
    { "tls_get_new-dtv", &TlsGetNewDtvTest },
    { "ftello-unflushed-append", &FtelloUnflushedAppendTestCompat },
    { "__ppoll_time64", &PpollTime64CompatTest },
    { "__signbit", &SignbitInnerTest },
    { "a64l", &A64lTest },
    { "a_stack_chk_fail", &AStackChkFailTestCompat },
    { "accept4", &Accept4Test },
    { "asctime", &AsctimeTest },
    { "asctime_r", &AsctimeRTestCompat },
    { "chmod", &ChmodTestCompat },
    { "clock_adjtime", &ClockAdjtimeTest },
    { "daemon", &DaemonTestCompat },
    { "difftime", &DifftimeTest },
    { "dl_iterate_phdr", &DlIteratePhdrTestCompat },
    { "dup3", &Dup3TestCompat },
    { "endmntent", &EndmntentTest },
    { "execle-env", &ExecleEnvTestCompat },
    { "faccessat", &FaccessatTest },
    { "fallocate", &FallocateTest },
    { "fatal_message", &FatalMessageTest },
    { "fchmod", &FchmodTest },
    { "fchmodat", &FchmodatTest },
    { "fchown", &FchownTest },
    { "fchownat", &FchownatTest },
    { "fdatasync", &FdatasyncTest },
    { "feupdateenv", &FeupdateenvTest },
    { "fgetxattr", &FgetxattrTest },
    { "finite", &FiniteTest },
    { "flock", &FlockTest },
    { "forkpty", &ForkptyTest },
    { "fsync", &FsyncTest },
    { "ftruncate", &FtruncateTest },
    { "functionalext_pow10", &FunctionalextPow10Test },
    { "futimes", &FutimesTest },
    { "futimesat", &FutimesatTest },
    { "getaddrinfo", &GetaddrinfoTest },
    { "getmntent", &GetmntentTest },
    { "getmntent_r", &GetmntentRTest },
    { "getpeername", &GetpeernameTest },
    { "getrusage", &GetrusageTest },
    { "getsockopt_network", &GetsockoptNetworkTest },
    { "gmtime", &GmtimeTest },
    { "gmtime_r", &GmtimeRTest },
    { "inotify", &InotifyTest },
    { "ioctl", &IoctlTest },
    { "iswalnum_l", &IswalnumLTest },
    { "iswgraph_l", &IswgraphLTest },
    { "ldso_debug_test", &LdsoDebugTestTest },
    { "ldso_memleak_check", &LdsoMemleakCheckTest },
    { "listen", &ListenTest },
    { "localtime", &LocaltimeTest },
    { "localtime_r", &LocaltimeRTest },
    { "lockf", &LockfTest },
    { "malloc-double-free-check", &MallocDoubleFreeCheckTest },
    { "malloc-encode-pointer", &MallocEncodePointerTest },
    { "malloc-modify-pointer", &MallocModifyPointerTest },
    { "malloc-safe-unlink", &MallocSafeUnlinkTest },
    { "membarrier", &MembarrierTest },
    { "mktime", &MktimeTest },
    { "mmap", &MmapTest },
    { "munmap", &MunmapTest },
    { "posix_spawn_file_actions_addopen", &PosixSpawnFileActionsAddopenTest },
    { "ppoll", &PpollTest },
    { "pthread-robust-detach", &PthreadRobustDetachTest },
    { "pthread_cond-smasher", &PthreadCondSmasherTest },
    { "pthread_guard_size", &PthreadGuardSizeTest },
    { "pthread_once-deadlock", &PthreadOnceDeadlockTest },
    { "pthread_rwlock-ebusy", &PthreadRwlockEbusyTest },
    { "read", &ReadTest },
    { "readv", &ReadvTest },
    { "recv", &RecvTest },
    { "recvmmsg", &RecvmmsgTest },
    { "recvmsg", &RecvmsgTest },
    { "renameat", &RenameatTest },
    { "resTraceFreeRegion", &ResTraceFreeRegionTest },
    { "resTraceMove", &ResTraceMoveTest },
    { "restrace", &RestraceTest },
    { "restraceExt", &RestraceExtTest },
    { "sched_setparam", &SchedSetparamTest },
    { "select", &SelectTest },
    { "sendfile", &SendfileTest },
    { "send", &SendTest },
    { "shutdown", &ShutdownTest },
    { "sigchain_intercept_pthread_sigmask", &SigchainInterceptPthreadSigmaskTest },
    { "sigchain_rm_special_handler", &SigchainRmSpecialHandlerTest },
    { "sigchain_set_pre_validation_ignore_thread_test", &SigchainSetPreValidationIgnoreThreadTestTest },
    { "strftime_ext", &StrftimeExtTest },
    { "strftime_l", &StrftimeLTest },
    { "strptime_ext", &StrptimeExtTest },
    { "symlinkat", &SymlinkatTest },
    { "timegm", &TimegmTest },
    { "ttyname_r", &TtynameRTest },
    { "ulimit", &UlimitTest },
    { "unlink", &UnlinkTest },
    { "unlinkat", &UnlinkatTest },
    { "utimensat", &UtimensatTest },
    { "utimes", &UtimesTest },
    { "clocale_mbfuncs", &ClocaleMbfuncsTest },
    { "dl_multithread_lock", &DlMultithreadLockTest },
    { "dl_multithread_test", &DlMultithreadTest },
    { "fdopen", &FdopenTest },
    { "fcntl", &FcntlTest },
    { "fopencookie_test", &FopencookieTest },
    { "inet_pton", &InetPtonTest },
    { "pthread_cond", &PthreadCondTest },
    { "pthread_mutex", &PthreadMutexTest },
    { "pthread_mutex_pi", &PthreadMutexPiTest },
    { "pthread_tsd", &PthreadTsdTest },
    { "search_tsearch", &SearchTsearchTest },
    { "sem_init", &SemInitTest },
    { "snprintf", &SnprintfTest },
    { "sscanf", &SscanfTest },
    { "string", &StringTest },
    { "string_memmem", &StringMemmemTest },
    { "string_memset", &StringMemsetTest },
    { "strtod", &StrtodTest },
    { "strtof", &StrtofTest },
    { "swprintf", &SwprintfTest },
    { "time", &TimeTest },
    { "tls_align", &TlsAlignTest },
    { "tls_align_dlopen", &TlsAlignDlopenTest },
    { "tls_init_dlopen", &TlsInitDlopenTest },
    { "tls_local_exec", &TlsLocalExecTest },
    { "call_once", &CallOnceTest },
    { "cnd_broadcast", &CndBroadcastTest },
    { "cnd_timedwait", &CndTimedwaitTest },
    { "cnd_wait", &CndWaitTest },
    { "mtx_timedlock", &MtxTimedlockTest },
    { "mtx_trylock", &MtxTrylockTest },
    { "mtx_unlock", &MtxUnlockTest },
    { "pthread_barrier_wait", &PthreadBarrierWaitTest },
    { "pthread_cond_init", &PthreadCondInitTest },
    { "pthread_cond_timedwait_sup", &PthreadCondTimedwaitSupTest },
    { "pthread_detach", &PthreadDetachTest },
    { "pthread_equal", &PthreadEqualTest },
    { "pthread_join", &PthreadJoinTest },
    { "pthread_mutex_timedlock", &PthreadMutexTimedlockTest },
    { "pthread_rwlock_timedrdlock", &PthreadRwlockTimedrdlockTest },
    { "pthread_rwlock_timedwrlock", &PthreadRwlockTimedwrlockTest },
    { "pthread_self", &PthreadSelfTest },
    { "pthread_setschedprio", &PthreadSetschedprioTest },
    { "pthread_spin_lock", &PthreadSpinLockTest },
    { "pthread_spin_trylock", &PthreadSpinTrylockTest },
    { "pthread_spin_unlock", &PthreadSpinUnlockTest },
    { "thrd_create", &ThrdCreateTest },
    { "thrd_current", &ThrdCurrentTest },
    { "thrd_detach", &ThrdDetachTest },
    { "thrd_equal", &ThrdEqualTest },
    { "thrd_join", &ThrdJoinTest },
    { "thrd_sleep", &ThrdSleepTest },
    { "asprintf", &AsprintfTest },
    { "dprintf", &DprintfTest },
    { "fgetln", &FgetlnTest },
    { "fgetpos", &FgetposTest },
    { "fgets", &FgetsTest },
    { "fgetws", &FgetwsTest },
    { "flockfile", &FlockfileTest },
    { "fprintf", &FprintfTest },
    { "fputc", &FputcTest },
    { "fputs", &FputsTest },
    { "fputwc", &FputwcTest },
    { "fputws", &FputwsTest },
    { "freopen", &FreopenTest },
    { "fseeko", &FseekoTest },
    { "ftell", &FtellTest },
    { "ftrylockfile", &FtrylockfileTest },
    { "funlockfile", &FunlockfileTest },
    { "fwide", &FwideTest },
    { "fwprintf", &FwprintfTest },
    { "fwrite", &FwriteTest },
    { "getc", &GetcTest },
    { "getc_unlocked", &GetcUnlockedTest },
    { "getchar", &GetcharTest },
    { "getchar_unlocked", &GetcharUnlockedTest },
    { "getdelim", &GetdelimTest },
    { "getline", &GetlineTest },
    { "putw", &PutwTest },
    { "remove", &RemoveTest },
    { "rename", &RenameTest },
    { "setbuf", &SetbufTest },
    { "setbuffer", &SetbufferTest },
    { "setlinebuf", &SetlinebufTest },
    { "setvbuf", &SetvbufTest },
    { "ungetwc", &UngetwcTest },
    { "vdprintf", &VdprintfTest },
    { "vfprintf", &VfprintfTest },
    { "vfscanf", &VfscanfTest },
    { "vfwprintf", &VfwprintfTest },
    { "vfwscanf", &VfwscanfTest },
    { "access", &AccessTest },
    { "fchdir", &FchdirTest },
    { "nice", &NiceTest },
    { "acosf", &AcosfTest },
    { "exp10", &Exp10Test },
    { "exp10f", &Exp10fTest },
    { "exp10l", &Exp10lTest },
    { "fdim", &FdimTest },
    { "fdimf", &FdimfTest },
    { "fmin", &FminTest },
    { "fminf", &FminfTest },
    { "fminl", &FminlTest },
    { "fmod", &FmodTest },
    { "fmodf", &FmodfTest },
    { "fmodl", &FmodlTest },
    { "j0", &J0Test },
    { "j0f", &J0fTest },
    { "j1", &J1Test },
    { "jn", &JnTest },
    { "jnf", &JnfTest },
    { "ldexp", &LdexpTest },
    { "ldexpf", &LdexpfTest },
    { "ldexpl", &LdexplTest },
    { "lgamma", &LgammaTest },
    { "lgamma_r", &LgammaRTest },
    { "lgammaf", &LgammafTest },
    { "lgammaf_r", &LgammafRTest },
    { "lgammal_r", &LgammalRTest },
    { "llrint", &LlrintTest },
    { "llrintf", &LlrintfTest },
    { "llrintl", &LlrintlTest },
    { "llround", &LlroundTest },
    { "llroundf", &LlroundfTest },
    { "llroundl", &LlroundlTest },
    { "log", &LogTest },
    { "log10", &Log10Test },
    { "log10f", &Log10fTest },
    { "log10l", &Log10lTest },
    { "log1p", &Log1pTest },
    { "log1pf", &Log1pfTest },
    { "log1pl", &Log1plTest },
    { "log2", &Log2Test },
    { "log2f", &Log2fTest },
    { "log2l", &Log2lTest },
    { "logb", &LogbTest },
    { "logbf", &LogbfTest },
    { "logbl", &LogblTest },
    { "logf", &LogfTest },
    { "logl", &LoglTest },
    { "lrint", &LrintTest },
    { "lrintf", &LrintfTest },
    { "lrintl", &LrintlTest },
    { "lround", &LroundTest },
    { "lroundf", &LroundfTest },
    { "lroundl", &LroundlTest },
    { "modf", &ModfTest },
    { "modff", &ModffTest },
    { "modfl", &ModflTest },
    { "nextafter", &NextafterTest },
    { "nextafterf", &NextafterfTest },
    { "nextafterl", &NextafterlTest },
    { "pow", &PowTest },
    { "pow10", &Pow10Test },
    { "pow10f", &Pow10fTest },
    { "pow10l", &Pow10lTest },
    { "powf", &PowfTest },
    { "powl", &PowlTest },
    { "remainder", &RemainderTest },
    { "remainderf", &RemainderfTest },
    { "remainderl", &RemainderlTest },
    { "remquo", &RemquoTest },
    { "remquof", &RemquofTest },
    { "remquol", &RemquolTest },
    { "round", &RoundTest },
    { "roundf", &RoundfTest },
    { "roundl", &RoundlTest },
    { "scalb", &ScalbTest },
    { "scalbf", &ScalbfTest },
    { "scalbln", &ScalblnTest },
    { "scalblnf", &ScalblnfTest },
    { "scalblnl", &ScalblnlTest },
    { "scalbn", &ScalbnTest },
    { "scalbnf", &ScalbnfTest },
    { "scalbnl", &ScalbnlTest },
    { "sin", &SinTest },
    { "sincos", &SincosTest },
    { "sincosf", &SincosfTest },
    { "sincosl", &SincoslTest },
    { "sinf", &SinfTest },
    { "sinh", &SinhTest },
    { "sinhf", &SinhfTest },
    { "sinhl", &SinhlTest },
    { "sinl", &SinlTest },
    { "tan", &TanTest },
    { "tanf", &TanfTest },
    { "tanh", &TanhTest },
    { "tanhf", &TanhfTest },
    { "tanhl", &TanhlTest },
    { "tanl", &TanlTest },
    { "trunc", &TruncTest },
    { "truncf", &TruncfTest },
    { "truncl", &TrunclTest },
    { "tgamma", &TgammaTest },
    { "tgammaf", &TgammafTest },
    { "y0", &Y0Test },
    { "y0f", &Y0fTest },
    { "y1", &Y1Test },
    { "y1f", &Y1fTest },
    { "yn", &YnTest },
    { "ynf", &YnfTest },
    { "iswalpha", &IswalphaTest },
    { "iswblank", &IswblankTest },
    { "iswcntrl", &IswcntrlTest },
    { "iswdigit", &IswdigitTest },
    { "iswlower", &IswlowerTest },
    { "iswprint", &IswprintTest },
    { "iswpunct", &IswpunctTest },
    { "iswspace", &IswspaceTest },
    { "iswupper", &IswupperTest },
    { "iswxdigit", &IswxdigitTest },
    { "towlower", &TowlowerTest },
    { "towupper", &TowupperTest },
    { "towupper_l", &TowupperLTest },
    { "__fpending", &FpendingTest },
    { "__fpurge", &FpurgeTest },
    { "__freadable", &FreadableTest },
    { "__freading", &FreadingTest },
    { "__fseterr", &FseterrTest },
    { "__fwritable", &FwritableTest },
    { "__fwriting", &FwritingTest },
    { "_flushlbf", &FlushlbfTest },
    { "a_cxa_atexit", &ACxaAtexitTest },
    { "double_exit", &DoubleExitTest },
    { "gethostbyname2", &Gethostbyname2Test },
    { "gethostbyname_r", &GethostbynameRTest },
    { "lfind", &LfindTest },
    { "tdestroy", &TdestroyTest },
    { "unittest_fatal_message", &UnittestFatalMessageTest },
    { "unittest_fatal_message_assert_fail_dialog", &UnittestFatalMessageAssertFailDialogTest },
    { "duplocale", &DuplocaleTest },
    { "__errno_location", &ErrnoLocationTest },
    { "semtimedop", &SemtimedopTest },
    { "pthread_internal_lock_info", &PthreadInternalLockInfoTest },
    { "wcsnrtombs", &WcsnrtombsTest },
    { "setitimer", &SetitimerTest },
    { "fsetpos", &FsetposTest },
    { "getwc", &GetwcTest },
    { "rewind", &RewindTest },
    { "functionalext_fcvt", &FunctionalextFcvtTest },
    { "invalid_param", &InvalidParamTest },
    { "pthread_fortify_test", &PthreadFortifyTestTest },
    { "select_test", &SelectTestTest },
    { "localeconv_sup", &LocaleconvSupTest },
    { "newlocale_sup", &NewlocaleSupTest },
    { "setlocale_sup", &SetlocaleSupTest },
    { "uselocale_sup", &UselocaleSupTest },
    { "pthread_create", &PthreadCreateTestTest },
    { "pthread_exit", &PthreadExitTestTest },
    { "pthread_getattr_np", &PthreadGetattrNpTestTest },
    { "pthread_getschedparam", &PthreadGetschedparamTestTest },
    { "pthread_getspecific", &PthreadGetspecificTestTest },
    { "pthread_key_create", &PthreadKeyCreateTestTest },
    { "pthread_mutex_lock", &PthreadMutexLockTestTest },
    { "pthread_mutex_unlock", &PthreadMutexUnlockTestTest },
    { "pthread_once", &PthreadOnceTestTest },
    { "pthread_setspecific", &PthreadSetspecificTestTest },
    { "pthread_setschedparam", &PthreadSetschedparamTestTest },
    { "alphasort", &AlphasortTest },
    { "fdopendir", &FdopendirTest },
    { "opendir", &OpendirTest },
    { "rewinddir", &RewinddirTest },
    { "seekdir", &SeekdirTest },
    { "telldir", &TelldirTest },
    { "wcstoimax", &WcstoimaxTest },
    { "wcstoumax", &WcstoumaxTest },
    { "qsort", &QsortTest },
    { "renameat2_test", &Renameat2TestTest },
    { "socket", &SocketTest },
    { "string_strchr", &StringStrchrTest },
    { "tgmath", &TgmathTest },
    { "memmem", &MemmemTest },
    { "memrchr", &MemrchrTest },
    { "stpcpy", &StpcpyTest },
    { "stpncpy", &StpncpyTest },
    { "strrchr", &StrrchrTest },
    { "wcscpy", &WcscpyTest },
    { "wcsdup", &WcsdupTest },
    { "wcsncpy", &WcsncpyTest },
    { "wcspbrk", &WcspbrkTest },
    { "creat", &CreatTest },
    { "openat", &OpenatTest },
    { "open", &OpenTest },
};
} // namespace

static int (*FindByName(const std::string& name))()
{
    auto it = kTestRegistry.find(name);
    if (it == kTestRegistry.end()) {
        return nullptr;
    }
    return it->second;
}

static int RunByNameForked(const std::string& name)
{
    auto* testFunc = FindByName(name);
    if (testFunc == nullptr) {
        return -K_RUN_TEST_NOT_FOUND;
    }

    pid_t pid = fork();
    if (pid < 0) {
        return -K_RUN_TEST_FORK_FAILED;
    }
    if (pid == 0) {
        int childRc = K_CHILD_EXIT_CAP;
        try {
            childRc = testFunc();
        } catch (...) {
            _exit(K_CHILD_EXIT_CAP);
        }
        if (childRc < 0) {
            _exit(K_CHILD_EXIT_CAP);
        }
        if (childRc > K_CHILD_EXIT_CAP) {
            _exit(K_CHILD_EXIT_CAP);
        }
        _exit(childRc);
    }

    int status = 0;
    if (waitpid(pid, &status, 0) < 0) {
        return -K_RUN_TEST_WAITPID_FAILED;
    }
    if (WIFEXITED(status)) {
        return WEXITSTATUS(status);
    }
    if (WIFSIGNALED(status)) {
        return K_SIGNAL_EXIT_BASE + WTERMSIG(status);
    }
    return -K_RUN_TEST_UNKNOWN_EXIT;
}

struct AsyncRunTestContext {
    napi_env env;
    napi_async_work work;
    napi_deferred deferred;
    std::string name;
    int rc;
};

static void ExecuteRunTestAsync(napi_env env, void* data)
{
    (void)env;
    auto* ctx = static_cast<AsyncRunTestContext*>(data);
    ctx->rc = RunByNameForked(ctx->name);
}

static void CompleteRunTestAsync(napi_env env, napi_status status, void* data)
{
    auto* ctx = static_cast<AsyncRunTestContext*>(data);
    napi_value result = nullptr;
    if (status == napi_ok) {
        napi_create_int32(env, ctx->rc, &result);
        napi_resolve_deferred(env, ctx->deferred, result);
    } else {
        napi_value msg = nullptr;
        napi_create_string_utf8(env, "runTestAsync failed", NAPI_AUTO_LENGTH, &msg);
        napi_reject_deferred(env, ctx->deferred, msg);
    }
    napi_delete_async_work(env, ctx->work);
    delete ctx;
}

static napi_value RunTestAsync(napi_env env, napi_callback_info info)
{
    return NapiTry(env, [&]() -> napi_value {
        size_t argc = 1;
        napi_value args[1] = { nullptr };
        napi_get_cb_info(env, info, &argc, args, nullptr, nullptr);
        if (argc < 1) {
            napi_throw_type_error(env, nullptr, "Argument missing");
            return nullptr;
        }

        size_t len = 0;
        napi_status st = napi_get_value_string_utf8(env, args[0], nullptr, 0, &len);
        if (st != napi_ok) {
            napi_throw_type_error(env, nullptr, "Argument must be a string");
            return nullptr;
        }

        auto* ctx = new AsyncRunTestContext();
        ctx->env = env;
        ctx->rc = -1;
        ctx->name.resize(len + 1);
        napi_get_value_string_utf8(env, args[0], &ctx->name[0], ctx->name.size(), &len);
        ctx->name.resize(len);

        napi_value promise = nullptr;
        napi_create_promise(env, &ctx->deferred, &promise);

        napi_value resourceName = nullptr;
        napi_create_string_utf8(env, "runTestAsync", NAPI_AUTO_LENGTH, &resourceName);
        napi_create_async_work(env, nullptr, resourceName, ExecuteRunTestAsync, CompleteRunTestAsync, ctx, &ctx->work);
        napi_queue_async_work(env, ctx->work);

        return promise;
    });
}

EXTERN_C_START
static napi_value Init(napi_env env, napi_value exports)
{
    napi_property_descriptor desc[] = {
        { "runTest", nullptr, RunTestAsync, nullptr, nullptr, nullptr, napi_default, nullptr },
    };
    napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc);
    return exports;
}
EXTERN_C_END

static napi_module demoModule = {
    .nm_version = 1,
    .nm_flags = 0,
    .nm_filename = nullptr,
    .nm_register_func = Init,
    .nm_modname = "entry",
    .nm_priv = nullptr,
    .reserved = { 0 },
};

extern "C" __attribute__((constructor)) void RegisterEntryModule(void)
{
    napi_module_register(&demoModule);
}
