/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "ImageKitSuccesTest.h"
#include "imageframeworkTest.h"
#include "imagepicture.h"
#include "imagepixelmapmdkTest.h"
#include "imagereceivermdkTest.h"
#include "ImagePixelMapMdk1Test.h"
#include "ImagePackerNativeTest.h"
#include "ImagePackerNative1Test.h"
#include "ImageSourceNativeErrorCodeTest.h"
#include "ImageEffectErrorCodeTest.h"
#include "ImageReceiverMdk1Test.h"
#include "ImageKitErrorCodeTest.h"
#include "ImageProcessingTest.h"
EXTERN_C_START

std::vector<napi_property_descriptor> desc = {
    {"ImagePackerCreate1", nullptr, ImagePackerCreate1, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImagePackerRelease", nullptr, ImagePackerRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureMetadataCreate1", nullptr, PictureMetadataCreate1, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureMetadataCreate2", nullptr, PictureMetadataCreate2, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureMetadataGetProperty1", nullptr, PictureMetadataGetProperty1, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PictureMetadataSetProperty1", nullptr, PictureMetadataSetProperty1, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PictureMetadataRelease1", nullptr, PictureMetadataRelease1, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureMetadataRelease2", nullptr, PictureMetadataRelease2, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureMetadataClone1", nullptr, PictureMetadataClone1, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"CreatePixelMapWithStride", nullptr, CreatePixelMapWithStride, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"CreateAlphaPixelMap", nullptr, CreateAlphaPixelMap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"GetBytesNumberPerRow", nullptr, GetBytesNumberPerRow, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"GetIsEditable", nullptr, GetIsEditable, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"IsSupportAlpha", nullptr, IsSupportAlpha, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"SetAlphaAble", nullptr, SetAlphaAble, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"GetDensity", nullptr, GetDensity, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"SetDensity", nullptr, SetDensity, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"SetOpacity", nullptr, SetOpacity, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapScale", nullptr, PixelMapScale, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ScaleWithAntiAliasing", nullptr, ScaleWithAntiAliasing, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapTranslate", nullptr, PixelMapTranslate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapRotate", nullptr, PixelMapRotate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapFlip", nullptr, PixelMapFlip, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapCrop", nullptr, PixelMapCrop, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapGetImageInfo", nullptr, PixelMapGetImageInfo, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapAccessPixels", nullptr, PixelMapAccessPixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapUnAccessPixels", nullptr, PixelMapUnAccessPixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"UnAccessPixels", nullptr, UnAccessPixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"GetImageInfoParameter", nullptr, GetImageInfoParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"CreateImageReceiver", nullptr, CreateImageReceiver, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"GetReceivingSurfaceId", nullptr, GetReceivingSurfaceId, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReadLatestImage", nullptr, ReadLatestImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReadNextImage", nullptr, ReadNextImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReceiverOn", nullptr, ReceiverOn, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReceiverGetSize", nullptr, ReceiverGetSize, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReceiverGetCapacity", nullptr, ReceiverGetCapacity, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReceiverGetFormat", nullptr, ReceiverGetFormat, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ReceiverRelease", nullptr, ReceiverRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreate", nullptr, ImageSourceCreate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreateFromUri", nullptr, ImageSourceCreateFromUri, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreateFromFd", nullptr, ImageSourceCreateFromFd, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreateFromData", nullptr, ImageSourceCreateFromData, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreateFromRawFile", nullptr, ImageSourceCreateFromRawFile, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSourceCreateIncremental", nullptr, ImageSourceCreateIncremental, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSourceCreateIncrementalFromData", nullptr, ImageSourceCreateIncrementalFromData, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageSourceGetSupportedFormats", nullptr, ImageSourceGetSupportedFormats, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSourceCreatePixelMap", nullptr, ImageSourceCreatePixelMap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceCreatePixelMapList", nullptr, ImageSourceCreatePixelMapList, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSource_GetDelayTime", nullptr, ImageSource_GetDelayTime, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceGetFrameCount", nullptr, ImageSourceGetFrameCount, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceGetImageInfo", nullptr, ImageSourceGetImageInfo, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceGetImageProperty", nullptr, ImageSourceGetImageProperty, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSourceModifyImageProperty", nullptr, ImageSourceModifyImageProperty, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageSourceUpdateData", nullptr, ImageSourceUpdateData, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageSourceRelease", nullptr, ImageSourceRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"packToData", nullptr, PackToData, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"create", nullptr, Create, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"packToFile", nullptr, PackToFile, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"release", nullptr, Release, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"JsCreateImageReceiver", nullptr, JsCreateImageReceiver, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"JsCreateImageReceiverOptions", nullptr, JsCreateImageReceiverOptions, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PictureNativeCreatePicture", nullptr, PictureNativeCreatePicture, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PictureNativeGetMainPixelmap", nullptr, PictureNativeGetMainPixelmap, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PictureNativeGetHdrComposedPixelmap", nullptr, PictureNativeGetHdrComposedPixelmap, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PictureNativeGetGainmapPixelmap", nullptr, PictureNativeGetGainmapPixelmap, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PictureNativeSetAuxiliaryPicture", nullptr, PictureNativeSetAuxiliaryPicture, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PictureNativeGetMetadata", nullptr, PictureNativeGetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureNativeSetMetadata", nullptr, PictureNativeSetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PictureNativeRelease", nullptr, PictureNativeRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"AuxiliaryPictureNativeCreate", nullptr, AuxiliaryPictureNativeCreate, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureNativeWritePixels", nullptr, AuxiliaryPictureNativeWritePixels, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeReadPixels", nullptr, AuxiliaryPictureNativeReadPixels, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeGetType", nullptr, AuxiliaryPictureNativeGetType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureNativeGetInfo", nullptr, AuxiliaryPictureNativeGetInfo, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureNativeSetInfo", nullptr, AuxiliaryPictureNativeSetInfo, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureNativeGetMetadata", nullptr, AuxiliaryPictureNativeGetMetadata, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeSetMetadata", nullptr, AuxiliaryPictureNativeSetMetadata, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeRelease", nullptr, AuxiliaryPictureNativeRelease, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoCreate", nullptr, AuxiliaryPictureInfoCreate, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoGetType", nullptr, AuxiliaryPictureInfoGetType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoSetType", nullptr, AuxiliaryPictureInfoSetType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoGetSize", nullptr, AuxiliaryPictureInfoGetSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoSetSize", nullptr, AuxiliaryPictureInfoSetSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoGetRowStride", nullptr, AuxiliaryPictureInfoGetRowStride, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoSetRowStride", nullptr, AuxiliaryPictureInfoSetRowStride, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoGetPixelFormat", nullptr, AuxiliaryPictureInfoGetPixelFormat, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoSetPixelFormat", nullptr, AuxiliaryPictureInfoSetPixelFormat, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoRelease", nullptr, AuxiliaryPictureInfoRelease, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"AuxiliaryPictureInfoSetTypeSuccess", nullptr, AuxiliaryPictureInfoSetTypeSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoCreateSuccess", nullptr, AuxiliaryPictureInfoCreateSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeCreateSuccess", nullptr, AuxiliaryPictureNativeCreateSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoGetSizeSucces", nullptr, AuxiliaryPictureInfoGetSizeSucces, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoSetSizeSuccess", nullptr, AuxiliaryPictureInfoSetSizeSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoGetRowStrideSuccess", nullptr, AuxiliaryPictureInfoGetRowStrideSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"AuxiliaryPictureInfoSetRowStrideSuccess", nullptr, AuxiliaryPictureInfoSetRowStrideSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"AuxiliaryPictureInfoGetPixelFormatSuccess", nullptr, AuxiliaryPictureInfoGetPixelFormatSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"AuxiliaryPictureInfoSetPixelFormatSuccess", nullptr, AuxiliaryPictureInfoSetPixelFormatSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"AuxiliaryPictureInfoReleaseSuccess", nullptr, AuxiliaryPictureInfoReleaseSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureInfoGetTypeSucess", nullptr, AuxiliaryPictureInfoGetTypeSucess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"AuxiliaryPictureNativeReleaseSuccess", nullptr, AuxiliaryPictureNativeReleaseSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapInitializationOptionsCreate", nullptr, PixelmapInitializationOptionsCreate, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapInitializationOptionsCreateSuccess", nullptr, PixelmapInitializationOptionsCreateSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetWidth", nullptr, PixelmapInitializationOptionsGetWidth, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapInitializationOptionsGetWidthSuccess", nullptr, PixelmapInitializationOptionsGetWidthSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetWidth", nullptr, PixelmapInitializationOptionsSetWidth, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapInitializationOptionsGetHeight", nullptr, PixelmapInitializationOptionsGetHeight, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetHeight", nullptr, PixelmapInitializationOptionsSetHeight, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetWidthSuccess", nullptr, PixelmapInitializationOptionsSetWidthSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetHeightSuccess", nullptr, PixelmapInitializationOptionsGetHeightSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetHeightSuccess", nullptr, PixelmapInitializationOptionsSetHeightSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetPixelFormatSuccess", nullptr, PixelmapInitializationOptionsGetPixelFormatSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetPixelFormatSuccess", nullptr, PixelmapInitializationOptionsSetPixelFormatSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetSrcPixelFormatSuccess", nullptr,
     PixelmapInitializationOptionsGetSrcPixelFormatSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetSrcPixelFormatSuccess", nullptr,
     PixelmapInitializationOptionsSetSrcPixelFormatSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetPixelFormat", nullptr, PixelmapInitializationOptionsGetPixelFormat, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetPixelFormat", nullptr, PixelmapInitializationOptionsSetPixelFormat, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetSrcPixelFormat", nullptr, PixelmapInitializationOptionsGetSrcPixelFormat, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetSrcPixelFormat", nullptr, PixelmapInitializationOptionsSetSrcPixelFormat, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetRowStrideSuccess", nullptr, PixelmapInitializationOptionsGetRowStrideSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetRowStride", nullptr, PixelmapInitializationOptionsGetRowStride, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetRowStride", nullptr, PixelmapInitializationOptionsSetRowStride, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetAlphaType", nullptr, PixelmapInitializationOptionsGetAlphaType, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetAlphaType", nullptr, PixelmapInitializationOptionsSetAlphaType, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetEditable", nullptr, PixelmapInitializationOptionsGetEditable, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetEditable", nullptr, PixelmapInitializationOptionsSetEditable, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsRelease", nullptr, PixelmapInitializationOptionsRelease, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoCreate", nullptr, PixelmapImageInfoCreate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapImageInfoGetWidth", nullptr, PixelmapImageInfoGetWidth, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapImageInfoGetHeight", nullptr, PixelmapImageInfoGetHeight, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapInitializationOptionsSetRowStrideSuccess", nullptr, PixelmapInitializationOptionsSetRowStrideSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetAlphaTypeSuccess", nullptr, PixelmapInitializationOptionsGetAlphaTypeSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetAlphaTypeSuccess", nullptr, PixelmapInitializationOptionsSetAlphaTypeSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsGetEditableSuccess", nullptr, PixelmapInitializationOptionsGetEditableSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsSetEditableSuccess", nullptr, PixelmapInitializationOptionsSetEditableSuccess,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapInitializationOptionsReleaseSuccess", nullptr, PixelmapInitializationOptionsReleaseSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapImageInfoCreateSuccess", nullptr, PixelmapImageInfoCreateSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapImageInfoGetWidthSuccess", nullptr, PixelmapImageInfoGetWidthSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetHeightSuccess", nullptr, PixelmapImageInfoGetHeightSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetAlphaModeSuccess", nullptr, PixelmapImageInfoGetAlphaModeSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetAlphaMode", nullptr, PixelmapImageInfoGetAlphaMode, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapImageInfoGetRowStrideSuccess", nullptr, PixelmapImageInfoGetRowStrideSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetRowStride", nullptr, PixelmapImageInfoGetRowStride, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapImageInfoGetPixelFormatSuccess", nullptr, PixelmapImageInfoGetPixelFormatSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapImageInfoGetPixelFormat", nullptr, PixelmapImageInfoGetPixelFormat, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetAlphaTypeSuccess", nullptr, PixelmapImageInfoGetAlphaTypeSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoGetAlphaType", nullptr, PixelmapImageInfoGetAlphaType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapImageInfoGetDynamicRangeSuccess", nullptr, PixelmapImageInfoGetDynamicRangeSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapImageInfoGetDynamicRange", nullptr, PixelmapImageInfoGetDynamicRange, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoReleaseSuccess", nullptr, PixelmapImageInfoReleaseSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapImageInfoRelease", nullptr, PixelmapImageInfoRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeCreatePixelmapSuccess", nullptr, PixelmapNativeCreatePixelmapSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeCreatePixelmap", nullptr, PixelmapNativeCreatePixelmap, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"CreatePixelmapUsingAllocator", nullptr, CreatePixelmapUsingAllocator, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ConvertPixelmapNativeToNapi", nullptr, ConvertPixelmapNativeToNapi, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ConvertPixelmapNativeToNapiSuccess", nullptr, ConvertPixelmapNativeToNapiSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ConvertPixelmapNativeFromNapi", nullptr, ConvertPixelmapNativeFromNapi, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeReadPixels", nullptr, PixelmapNativeReadPixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeWritePixels", nullptr, PixelmapNativeWritePixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeGetArgbPixelsSuccess", nullptr, PixelmapNativeGetArgbPixelsSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeGetArgbPixels", nullptr, PixelmapNativeGetArgbPixels, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeToSdr", nullptr, PixelmapNativeToSdr, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeGetImageInfo", nullptr, PixelmapNativeGetImageInfo, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeOpacitySuccess", nullptr, PixelmapNativeOpacitySuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeOpacity", nullptr, PixelmapNativeOpacity, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeScaleSuccess", nullptr, PixelmapNativeScaleSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeScale", nullptr, PixelmapNativeScale, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeScaleWithAntiAliasing", nullptr, PixelmapNativeScaleWithAntiAliasing, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"CreateScaledPixelMap", nullptr, CreateScaledPixelMap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"Translate", nullptr, Translate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeRotateSuccess", nullptr, PixelmapNativeRotateSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeRotate", nullptr, PixelmapNativeRotate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeFlipSuccess", nullptr, PixelmapNativeFlipSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeFlip", nullptr, PixelmapNativeFlip, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeCrop", nullptr, PixelmapNativeCrop, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeReleaseSuccess", nullptr, PixelmapNativeReleaseSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeRelease", nullptr, PixelmapNativeRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"CreateScaledPixelMapWithAntiAliasing", nullptr, CreateScaledPixelMapWithAntiAliasing, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeDestroySuccess", nullptr, PixelmapNativeDestroySuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeDestroy", nullptr, PixelmapNativeDestroy, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeConvertAlphaFormat", nullptr, PixelmapNativeConvertAlphaFormat, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeCreateEmptyPixelmapSuccess", nullptr, PixelmapNativeCreateEmptyPixelmapSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelmapNativeCreateEmptyPixelmap", nullptr, PixelmapNativeCreateEmptyPixelmap, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeCreateEmptyPixelmapUsingAllocator", nullptr, PixelmapNativeCreateEmptyPixelmapUsingAllocator,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeGetMetadata", nullptr, PixelmapNativeGetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeSetMetadata", nullptr, PixelmapNativeSetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeGetNativeBuffer", nullptr, PixelmapNativeGetNativeBuffer, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeGetColorSpaceNative", nullptr, PixelmapNativeGetColorSpaceNative, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeSetColorSpaceNative", nullptr, PixelmapNativeSetColorSpaceNative, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeSetMemoryName", nullptr, PixelmapNativeSetMemoryName, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeGetByteCountSuccess", nullptr, PixelmapNativeGetByteCountSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeGetByteCount", nullptr, PixelmapNativeGetByteCount, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeGetAllocationByteCountSuccess", nullptr, PixelmapNativeGetAllocationByteCountSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelmapNativeGetAllocationByteCount", nullptr, PixelmapNativeGetAllocationByteCount, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeAccessPixelsSuccess", nullptr, PixelmapNativeAccessPixelsSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeAccessPixels", nullptr, PixelmapNativeAccessPixels, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelmapNativeUnaccessPixelsSuccess", nullptr, PixelmapNativeUnaccessPixelsSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelmapNativeUnaccessPixels", nullptr, PixelmapNativeUnaccessPixels, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingCreateSuccess", nullptr, ImageProcessingCreateSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingDestroySuccess", nullptr, ImageProcessingDestroySuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingDestroy", nullptr, ImageProcessingDestroy, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageProcessingSetParameterSuccess", nullptr, ImageProcessingSetParameterSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingSetParameter", nullptr, ImageProcessingSetParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingGetParameterSuccess", nullptr, ImageProcessingGetParameterSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingGetParameter", nullptr, ImageProcessingGetParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingConvertColorSpaceValue", nullptr, ImageProcessingConvertColorSpaceValue, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingConvertColorSpace", nullptr, ImageProcessingConvertColorSpace, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingComposeValue", nullptr, ImageProcessingComposeValue, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingCompose", nullptr, ImageProcessingCompose, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageProcessingDecomposeValue", nullptr, ImageProcessingDecomposeValue, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingDecompose", nullptr, ImageProcessingDecompose, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"ImageProcessingGenerateMetadataValue", nullptr, ImageProcessingGenerateMetadataValue, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingGenerateMetadata", nullptr, ImageProcessingGenerateMetadata, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingEnhanceDetailValue", nullptr, ImageProcessingEnhanceDetailValue, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageProcessingEnhanceDetail", nullptr, ImageProcessingEnhanceDetail, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingCreateInstance", nullptr, ImageProcessingCreateInstance, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageProcessingDeinitializeEnvironment", nullptr, ImageProcessingDeinitializeEnvironment, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelMapScaleWithAntiAliasingNone", nullptr, PixelMapScaleWithAntiAliasingNone, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapScaleWithAntiAliasingLow", nullptr, PixelMapScaleWithAntiAliasingLow, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapScaleWithAntiAliasingMedium", nullptr, PixelMapScaleWithAntiAliasingMedium, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"OHImageEffectInsertFilterByFilterEffectSuccess", nullptr, OHImageEffectInsertFilterByFilterEffectSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"OHImageEffectConfigureEffectParamError", nullptr, OHImageEffectConfigureEffectParamError, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"OHImageEffectSetInputNativeBufferErrorCode", nullptr, OHImageEffectSetInputNativeBufferErrorCode, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"OHImageEffectSetOutputNativeBufferErrorCode", nullptr, OHImageEffectSetOutputNativeBufferErrorCode, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"OHImageEffectSetInputPictureErrorCode", nullptr, OHImageEffectSetInputPictureErrorCode, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"OHImageEffectSetOutputPictureErrorCode", nullptr, OHImageEffectSetOutputPictureErrorCode, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"OHImageEffectStartErrorCode", nullptr, OHImageEffectStartErrorCode, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"OHImageEffectStopErrorCode", nullptr, OHImageEffectStopErrorCode, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageEffectErrorCodeErrorParamInvalid", nullptr, ImageEffectErrorCodeErrorParamInvalid, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"ImageEffectErrorCodeParamError", nullptr, ImageEffectErrorCodeParamError, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageEffectErrorCodeKeyError", nullptr, ImageEffectErrorCodeKeyError, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageEffectDataTypeUnknown", nullptr, ImageEffectDataTypeUnknown, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"ImageEffectBufferTypeUnknown", nullptr, ImageEffectBufferTypeUnknown, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"OHEffectFilterSetValueErrorCode", nullptr, OHEffectFilterSetValueErrorCode, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"OHEffectFilterGetValueErrorCode", nullptr, OHEffectFilterGetValueErrorCode, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"OHImageEffectImageEffectRegion", nullptr, OHImageEffectImageEffectRegion, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"OHImageEffectImageEffectSize", nullptr, OHImageEffectImageEffectSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"OHEffectFilterLookupFiltersFilterNames", nullptr, OHEffectFilterLookupFiltersFilterNames, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmapNative_AntiAliasingLevel_NONE", nullptr, OH_PixelmapNative_AntiAliasingLevel_NONE, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmapNative_AntiAliasingLevel_LOW", nullptr, OH_PixelmapNative_AntiAliasingLevel_LOW, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmapNative_AntiAliasingLevel_MEDIUM", nullptr, OH_PixelmapNative_AntiAliasingLevel_MEDIUM, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrMetadataKey_HDR_STATIC_METADATA", nullptr, OH_Pixelmap_HdrMetadataKey_HDR_STATIC_METADATA, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrMetadataKey_HDR_DYNAMIC_METADATA", nullptr, OH_Pixelmap_HdrMetadataKey_HDR_DYNAMIC_METADATA, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrMetadataKey_HDR_GAINMAP_METADATA", nullptr, OH_Pixelmap_HdrMetadataKey_HDR_GAINMAP_METADATA, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"imageErrorCode_IMAGE_DMA_NOT_EXIST", nullptr, Image_ErrorCode_IMAGE_DMA_NOT_EXIST, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrMetadataType_NONE", nullptr, OH_Pixelmap_HdrMetadataType_NONE, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrMetadataType_BASE", nullptr, OH_Pixelmap_HdrMetadataType_BASE, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrMetadataType_GAINMAP", nullptr, OH_Pixelmap_HdrMetadataType_GAINMAP, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrMetadataType_ALTERNATE", nullptr, OH_Pixelmap_HdrMetadataType_ALTERNATE, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrMetadataType_ALTERNATE", nullptr, OH_Pixelmap_HdrMetadataType_ALTERNATE, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_displayPrimariesX", nullptr, OH_Pixelmap_HdrStaticMetadata_displayPrimariesX, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_displayPrimariesY", nullptr, OH_Pixelmap_HdrStaticMetadata_displayPrimariesY, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_whitePointX", nullptr, OH_Pixelmap_HdrStaticMetadata_whitePointX, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_whitePointY", nullptr, OH_Pixelmap_HdrStaticMetadata_whitePointY, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_maxLuminance", nullptr, OH_Pixelmap_HdrStaticMetadata_maxLuminance, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_minLuminance", nullptr, OH_Pixelmap_HdrStaticMetadata_minLuminance, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_maxContentLightLevel", nullptr, OH_Pixelmap_HdrStaticMetadata_maxContentLightLevel,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrStaticMetadata_maxFrameAverageLightLevel", nullptr,
     OH_Pixelmap_HdrStaticMetadata_maxFrameAverageLightLevel, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrDynamicMetadata_data", nullptr, OH_Pixelmap_HdrDynamicMetadata_data, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrDynamicMetadata_length", nullptr, OH_Pixelmap_HdrDynamicMetadata_length, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_writerVersion", nullptr, OH_Pixelmap_HdrGainmapMetadata_writerVersion, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_miniVersion", nullptr, OH_Pixelmap_HdrGainmapMetadata_miniVersion, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_gainmapChannelNum", nullptr, OH_Pixelmap_HdrGainmapMetadata_gainmapChannelNum,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_useBaseColorFlag", nullptr, OH_Pixelmap_HdrGainmapMetadata_useBaseColorFlag, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_baseHeadroom", nullptr, OH_Pixelmap_HdrGainmapMetadata_baseHeadroom, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_alternateHeadroom", nullptr, OH_Pixelmap_HdrGainmapMetadata_alternateHeadroom,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_gainmapMax", nullptr, OH_Pixelmap_HdrGainmapMetadata_gainmapMax, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_gainmapMin", nullptr, OH_Pixelmap_HdrGainmapMetadata_gainmapMin, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_gamma", nullptr, OH_Pixelmap_HdrGainmapMetadata_gamma, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_baselineOffset", nullptr, OH_Pixelmap_HdrGainmapMetadata_baselineOffset, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelmap_HdrGainmapMetadata_alternateOffset", nullptr, OH_Pixelmap_HdrGainmapMetadata_alternateOffset, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_RGB_565", nullptr, PixelFormat_RGB_565, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_RGB_888", nullptr, PixelFormat_RGB_888, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_ALPHA_8", nullptr, PixelFormat_ALPHA_8, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_RGBA_F16", nullptr, PixelFormat_RGBA_F16, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_NV21", nullptr, PixelFormat_NV21, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_NV12", nullptr, PixelFormat_NV12, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_RGBA_1010102", nullptr, PixelFormat_RGBA_1010102, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_YCBCR_P010", nullptr, PixelFormat_YCBCR_P010, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"pixelFormat_YCRCB_P010", nullptr, PixelFormat_YCRCB_P010, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"JSImageImageAllocatorModeDmaCode", nullptr, JSImageImageAllocatorModeDmaCode, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"JSImageImageAllocatorModeSharedMemoryCode", nullptr, JSImageImageAllocatorModeSharedMemoryCode, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"JSImagePixelmapAlphaTypeOpaqueCode", nullptr, JSImagePixelmapAlphaTypeOpaqueCode, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"JSImagePixelmapAlphaTypeUnpremultipliedCode", nullptr, JSImagePixelmapAlphaTypeUnpremultipliedCode, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"JSImagePixelmapHdrMetadataValueTypeCode", nullptr, JSImagePixelmapHdrMetadataValueTypeCode, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"JSImagePixelmapHdrMetadataValueStaticMetadataCode", nullptr, JSImagePixelmapHdrMetadataValueStaticMetadataCode,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"JSImagePixelmapHdrMetadataValueDynamicMetadataCode", nullptr, JSImagePixelmapHdrMetadataValueDynamicMetadataCode,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"JSImagePixelmapHdrMetadataValueGainmapMetadataCode", nullptr, JSImagePixelmapHdrMetadataValueGainmapMetadataCode,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createImageReceiver", nullptr, JsCreateImageReceiverMdk, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageFormat", nullptr, JsImageFormat, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageFormatBadParameter", nullptr, JsImageFormatBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageFormatJniEnvAbnormal", nullptr, JsImageFormatJniEnvAbnormal, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"readLatestImage", nullptr, JsReadLatestImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"on", nullptr, JsOn, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"receiverRelease", nullptr, JsReceiverRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageFormatYcbcr422Sp", nullptr, JsImageFormatYcbcr422Sp, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageFormatJPEG", nullptr, JsImageFormatJPEG, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageComponentFormatYUVY", nullptr, JsImageComponentFormatYUVY, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageComponentFormatYUVU", nullptr, JsImageComponentFormatYUVU, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageComponentFormatYUVV", nullptr, JsImageComponentFormatYUVV, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageComponentFormatJPEG", nullptr, JsImageComponentFormatJPEG, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageGetComponent", nullptr, JsImageGetComponent, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageGetComponentBadParameter", nullptr, JsImageGetComponentBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"imageGetComponentJniEnvAbnormal", nullptr, JsImageGetComponentJniEnvAbnormal, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"imageClipRect", nullptr, JsImageClipRect, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageClipBadParameter", nullptr, JsImageClipBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageSize", nullptr, JsImageSize, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageSizeJniEnvAbnormal", nullptr, JsImageSizeJniEnvAbnormal, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"imageRelease", nullptr, JsImageRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createPixelMapSuccess", nullptr, CreatePixelMapSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createPixelMapThirdpartSkiaError", nullptr, CreatePixelMapThirdpartSkiaError, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverOptionsGetCapacity", nullptr, JsImageReceiverOptionsGetCapacity, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverOptionsSetCapacity", nullptr, JsImageReceiverOptionsSetCapacity, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetReceivingSurfaceId", nullptr, JsGetReceivingSurfaceId, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsReadNextImage", nullptr, JsImageReceiverNativeReadNextImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsCreateImageReceiverOptions", nullptr, JsImagePackerCreateImageReceiverOptions, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsCreateImageReceiver", nullptr, JsImageReceiverNativeCreateImageReceiver, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsReadLatestImage", nullptr, JsImageReceiverNativeReadLatestImage, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeOn", nullptr, JsImageReceiverNativeOn, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageSize", nullptr, JsGetImageSize, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageSizeBadParameter", nullptr, JsGetImageSizeBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsGetImageComponentTypes", nullptr, JsGetImageComponentTypes, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageByteBuffer", nullptr, JsGetImageByteBuffer, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageByteBufferBadParameter", nullptr, JsGetImageByteBufferBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetImageBufferSize", nullptr, JsGetImageBufferSize, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageBufferSizeBadParameter", nullptr, JsGetImageBufferSizeBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetImageRowStride", nullptr, JsGetImageRowStride, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageRowStrideBadParameter", nullptr, JsGetImageRowStrideBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetImagePixelStride", nullptr, JsGetImagePixelStride, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImagePixelStrideBadParameter", nullptr, JsGetImagePixelStrideBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetImageTimestamp", nullptr, JsGetImageTimestamp, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetImageTimestampBadParameter", nullptr, JsGetImageTimestampBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsReleaseImage", nullptr, JsReleaseImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsReleaseImageBadParameter", nullptr, JsReleaseImageBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jSImagePackerDynamicRangeAuto", nullptr, JSImagePackerDynamicRangeAuto, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jSImagePackerDynamicRangeSdr", nullptr, JSImagePackerDynamicRangeSdr, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsIOHPackingOptionsCreate", nullptr, JSIOHPackingOptionsCreate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createPackingOptions", nullptr, CreatePackingOptions, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetMimeType", nullptr, JSPackingOptionsSetMimeType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackingOptionsSetMimeTypeImageAllocFailed", nullptr, JSPackingOptionsSetMimeTypeImageAllocFailed, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetMimeTypeImageBadParameter", nullptr, JSPackingOptionsSetMimeTypeImageBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetMimeType", nullptr, JSPackingOptionsGetMimeType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackingOptionsGetMimeTypeImageAllocFailed", nullptr, JSPackingOptionsGetMimeTypeImageAllocFailed, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetMimeTypeImageBadParameter", nullptr, JSPackingOptionsGetMimeTypeImageBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetMimeTypeNull", nullptr, JSPackingOptionsGetMimeTypeNull, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackingOptionsGetMimeTypeNullInvalidParameter", nullptr, JSPackingOptionsGetMimeTypeNullInvalidParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetQuality", nullptr, JSPackingOptionsGetQuality, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackingOptionsGetQualityBadParameter", nullptr, JSPackingOptionsGetQualityBadParameter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetQuality", nullptr, JSPackingOptionsSetQuality, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackingOptionsSetQualityBadParameter", nullptr, JSPackingOptionsSetQualityBadParameter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetNeedsPackProperties", nullptr, JSPackingOptionsSetNeedsPackProperties, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetNeedsPackPropertiesBadParameter", nullptr, JSPackingOptionsSetNeedsPackPropertiesBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetNeedsPackProperties", nullptr, JSPackingOptionsGetNeedsPackProperties, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetNeedsPackPropertiesBadParameter", nullptr, JSPackingOptionsGetNeedsPackPropertiesBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetDesiredDynamicRange", nullptr, JSPackingOptionsSetDesiredDynamicRange, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsSetDesiredDynamicRangeBadParameter", nullptr, JSPackingOptionsSetDesiredDynamicRangeBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetDesiredDynamicRange", nullptr, JSPackingOptionsGetDesiredDynamicRange, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsGetDesiredDynamicRangeBadParameter", nullptr, JSPackingOptionsGetDesiredDynamicRangeBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsRelease", nullptr, JSPackingOptionsRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsReleaseBadParameter", nullptr, JSPackingOptionsReleaseBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackingOptionsForSequenceCreate", nullptr, JSPackingOptionsForSequenceCreate, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetFrameCount", nullptr, JSPackingOptionsForSequenceSetFrameCount, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetFrameCountBadParameter", nullptr,
     JSPackingOptionsForSequenceSetFrameCountBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetFrameCount", nullptr, JSPackingOptionsForSequenceGetFrameCount, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetFrameCountBadParameter", nullptr,
     JSPackingOptionsForSequenceGetFrameCountBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetDelayTimeList", nullptr, JSPackingOptionsForSequenceSetDelayTimeList, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetDelayTimeListBadParameter", nullptr,
     JSPackingOptionsForSequenceSetDelayTimeListBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetDelayTimeList", nullptr, JSPackingOptionsForSequenceGetDelayTimeList, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetDelayTimeListBadParameter", nullptr,
     JSPackingOptionsForSequenceGetDelayTimeListBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetDisposalTypes", nullptr, JSPackingOptionsForSequenceSetDisposalTypes, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetDisposalTypesBadParameter", nullptr,
     JSPackingOptionsForSequenceSetDisposalTypesBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetDisposalTypes", nullptr, JSPackingOptionsForSequenceGetDisposalTypes, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetDisposalTypesBadParameter", nullptr,
     JSPackingOptionsForSequenceGetDisposalTypesBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetLoopCount", nullptr, JSPackingOptionsForSequenceSetLoopCount, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceSetLoopCountBadParameter", nullptr,
     JSPackingOptionsForSequenceSetLoopCountBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetLoopCount", nullptr, JSPackingOptionsForSequenceGetLoopCount, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceGetLoopCountBadParameter", nullptr,
     JSPackingOptionsForSequenceGetLoopCountBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackingOptionsForSequenceRelease", nullptr, JSPackingOptionsForSequenceRelease, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackingOptionsForSequenceReleaseBadParameter", nullptr, JSPackingOptionsForSequenceReleaseBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImagePackerNativeCreate", nullptr, JSImagePackerNativeCreate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"packerCreate", nullptr, PackerCreate, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createFromFd", nullptr, CreateFromFd, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createDecodingOptions", nullptr, CreateDecodingOptions, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"createPixelMapWithImageSoure", nullptr, CreatePixelMapWithImageSoure, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackToDataFromImageSource", nullptr, JSPackToDataFromImageSource, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackToDataFromImageSourceBadParamter", nullptr, JSPackToDataFromImageSourceBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackToDataFromPixelmap", nullptr, JSPackToDataFromPixelmap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackToDataFromPixelmapBadParamter", nullptr, JSPackToDataFromPixelmapBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackToDataFromPicture", nullptr, JSPackToDataFromPicture, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackToDataFromPictureBadParamter", nullptr, JSPackToDataFromPictureBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackToDataFromPixelmapSequence", nullptr, JSPackToDataFromPixelmapSequence, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackToDataFromPixelmapSequenceBadParamter", nullptr, JSPackToDataFromPixelmapSequenceBadParamter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsPackToFileFromImageSource", nullptr, JSPackToFileFromImageSource, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsPackToFileFromImageSourceBadParamter", nullptr, JSPackToFileFromImageSourceBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsPackToFileFromPixelmap", nullptr, JSPackToFileFromPixelmap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackToFileFromPixelmapBadParamter", nullptr, JSPackToFileFromPixelmapBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackToFileFromPicture", nullptr, JSPackToFileFromPicture, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsPackToFileFromPictureBadParamter", nullptr, JSPackToFileFromPictureBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsPackToFileFromPixelmapSequenceBadParamter", nullptr, JSPackToFileFromPixelmapSequenceBadParamter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImagePackerNativeRelease", nullptr, JSImagePackerNativeRelease, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImagePackerNativeReleaseBadParamter", nullptr, JSImagePackerNativeReleaseBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsGetSupportedFormats", nullptr, JSGetSupportedFormats, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsGetSupportedFormatsBadParamter", nullptr, JSGetSupportedFormatsBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverOptionsCreate", nullptr, JSImageReceiverOptionsCreate, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverOptionsCreateBadParamter", nullptr, JSImageReceiverOptionsCreateBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageReceiverOptionsGetSize", nullptr, JSImageReceiverOptionsGetSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverOptionsSetSize", nullptr, JSImageReceiverOptionsSetSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverOptionsSetSizeBadParamter", nullptr, JSImageReceiverOptionsSetSizeBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageReceiverOptionsGetCapacitySuccess", nullptr, JSImageReceiverOptionsGetCapacitySuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageReceiverOptionsSetCapacitySuccess", nullptr, JSImageReceiverOptionsSetCapacitySuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageReceiverOptionsSetCapacityBadParamter", nullptr, JSImageReceiverOptionsSetCapacityBadParamter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverOptionsRelease", nullptr, JSImageReceiverOptionsRelease, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeCreate", nullptr, JSImageReceiverNativeCreate, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeCreateBadParamter", nullptr, JSImageReceiverNativeCreateBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeGetReceivingSurfaceId", nullptr, JSImageReceiverNativeGetReceivingSurfaceId, nullptr,
     nullptr, nullptr, napi_default, nullptr},

    {"jsImageReceiverNativeReadLatestImageBadParamter", nullptr, JSImageReceiverNativeReadLatestImageBadParamter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeReadLatestImageUnknownError", nullptr, JSImageReceiverNativeReadLatestImageUnknownError,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeReadNextImageBadParamter", nullptr, JSImageReceiverNativeReadNextImageBadParamter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeReadNextImageUnknownError", nullptr, JSImageReceiverNativeReadNextImageUnknownError, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeOnSuccess", nullptr, JSImageReceiverNativeOnSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeOnBadParamter", nullptr, JSImageReceiverNativeOnBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverNativeOff", nullptr, JSImageReceiverNativeOff, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeOffBadParamter", nullptr, JSImageReceiverNativeOffBadParamter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverNativeOnImageArrive", nullptr, JSImageReceiverNativeOnImageArrive, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverNativeOnImageArriveInvaildParamter", nullptr, JSImageReceiverNativeOnImageArriveInvaildParamter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeOffImageArrive", nullptr, JSImageReceiverNativeOffImageArrive, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverNativeOffImageArriveInvaildParamter", nullptr, JSImageReceiverNativeOffImageArriveInvaildParamter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageReceiverNativeGetSize", nullptr, JSImageReceiverNativeGetSize, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeGetCapacity", nullptr, JSImageReceiverNativeGetCapacity, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageReceiverNativeRelease", nullptr, JSImageReceiverNativeRelease, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageReceiverNativeReleaseBadParamter", nullptr, JSImageReceiverNativeReleaseBadParamter, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageDynamicRangeAuto", nullptr, JSImageSoureNativeImageDynamicRangeAuto, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageDynamicRangeSDR", nullptr, JSImageSoureNativeImageDynamicRangeSDR, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageDynamicRangeHDR", nullptr, JSImageSoureNativeImageDynamicRangeHDR, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageAllocatorTypeAuto", nullptr, JSImageSoureNativeImageAllocatorTypeAuto, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageAllocatorTypeDMA", nullptr, JSImageSoureNativeImageAllocatorTypeDMA, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageAllocatorTypeShareMemory", nullptr, JSImageSoureNativeImageAllocatorTypeShareMemory,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageCropAndScaleStrategyScaleFirst", nullptr,
     JSImageSoureNativeImageCropAndScaleStrategyScaleFirst, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageCropAndScaleStrategyCropFirst", nullptr,
     JSImageSoureNativeImageCropAndScaleStrategyCropFirst, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetWidth", nullptr, JSImageSoureNativeImageSourceInfoGetWidth, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetWidthBadParameter", nullptr,
     JSImageSoureNativeImageSourceInfoGetWidthBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetHeight", nullptr, JSImageSoureNativeImageSourceInfoGetHeight, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetHeightBadParameter", nullptr,
     JSImageSoureNativeImageSourceInfoGetHeightBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetDynamicRange", nullptr, JSImageSoureNativeImageSourceInfoGetDynamicRange,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetDynamicRangeBadParameter", nullptr,
     JSImageSoureNativeImageSourceInfoGetDynamicRangeBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoGetMimeType", nullptr, JSImageSoureNativeImageSourceInfoGetMimeType, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoRelease", nullptr, JSImageSoureNativeImageSourceInfoRelease, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeImageSourceInfoReleasBadParameter", nullptr,
     JSImageSoureNativeImageSourceInfoReleasBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetPixelFormat", nullptr, JSImageSoureNativeDecodingOptionsGetPixelFormat,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetPixelFormatBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetPixelFormatBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetPixelFormatBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetPixelFormatBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetIndex", nullptr, JSImageSoureNativeDecodingOptionsGetIndex, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetIndexBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetIndexBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetIndex", nullptr, JSImageSoureNativeDecodingOptionsSetIndex, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetIndexBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetIndexBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetRotate", nullptr, JSImageSoureNativeDecodingOptionsGetRotate, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetRotateBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetRotateBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetRotate", nullptr, JSImageSoureNativeDecodingOptionsSetRotate, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetRotateBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetRotateBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredSize", nullptr, JSImageSoureNativeDecodingOptionsGetDesiredSize,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredSizeBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredSizeBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredSizeBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredSizeBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredRegion", nullptr, JSImageSoureNativeDecodingOptionsGetDesiredRegion,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredRegionBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredRegionBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredRegion", nullptr, JSImageSoureNativeDecodingOptionsSetDesiredRegion,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredRegionBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredRegionBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredDynamicRange", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredDynamicRange, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredDynamicRangeBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredDynamicRangeBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredDynamicRange", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredDynamicRange, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredDynamicRangeBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredDynamicRangeBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsSetCropAndScaleStrategy", nullptr,
     JSImageSoureNativeDecodingOptionsSetCropAndScaleStrategy, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetCropAndScaleStrategyBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsSetCropAndScaleStrategyBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsGetCropAndScaleStrategy", nullptr,
     JSImageSoureNativeDecodingOptionsGetCropAndScaleStrategy, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetCropAndScaleStrategyBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsGetCropAndScaleStrategyBadParameter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsSetCropRegionInvaildParamter", nullptr,
     JSImageSoureNativeDecodingOptionsSetCropRegionInvaildParamter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetCropRegionInvaildParamter", nullptr,
     JSImageSoureNativeDecodingOptionsGetCropRegionInvaildParamter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredColorSpace", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredColorSpace, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsGetDesiredColorSpaceInvaildParamter", nullptr,
     JSImageSoureNativeDecodingOptionsGetDesiredColorSpaceInvaildParamter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredColorSpace", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredColorSpace, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsSetDesiredColorSpaceInvaildParamter", nullptr,
     JSImageSoureNativeDecodingOptionsSetDesiredColorSpaceInvaildParamter, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsRelease", nullptr, JSImageSoureNativeDecodingOptionsRelease, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsReleaseBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsReleaseBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromUri", nullptr, JSImageSoureNativeCreateFromUri, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeCreateFromUriBadParameter", nullptr, JSImageSoureNativeCreateFromUriBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromFdBadParameter", nullptr, JSImageSoureNativeCreateFromFdBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromData", nullptr, JSImageSoureNativeCreateFromData, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeCreateFromDataBadParameter", nullptr, JSImageSoureNativeCreateFromDataBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromDataWithUserBuffer", nullptr, JSImageSoureNativeCreateFromDataWithUserBuffer, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromDataWithUserBufferInvaildParamter", nullptr,
     JSImageSoureNativeCreateFromDataWithUserBufferInvaildParamter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreateFromRawFile", nullptr, JSImageSoureNativeCreateFromRawFile, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeCreateFromRawFileBadParameter", nullptr, JSImageSoureNativeCreateFromRawFileBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePixelmapBadParameter", nullptr, JSImageSoureNativeCreatePixelmapBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePixelmapUsingAllocatorBadParameter", nullptr,
     JSImageSoureNativeCreatePixelmapUsingAllocatorBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePixelmapUsingAllocatorUnsuportedAllocatorType", nullptr,
     JSImageSoureNativeCreatePixelmapUsingAllocatorUnsuportedAllocatorType, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeCreatePixelmapList", nullptr, JSImageSoureNativeCreatePixelmapList, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeCreatePixelmapListBadParameter", nullptr, JSImageSoureNativeCreatePixelmapListBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePicture", nullptr, JSImageSoureNativeCreatePicture, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeCreatePictureBadParameter", nullptr, JSImageSoureNativeCreatePictureBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePictureAtIndex", nullptr, JSImageSoureNativeCreatePictureAtIndex, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePictureAtIndexBadSource", nullptr, JSImageSoureNativeCreatePictureAtIndexBadSource,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeCreatePictureAtIndexUnsuportedOptions", nullptr,
     JSImageSoureNativeCreatePictureAtIndexUnsuportedOptions, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeGetDelayTimeList", nullptr, JSImageSoureNativeGetDelayTimeList, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeGetDelayTimeListBadParameter", nullptr, JSImageSoureNativeGetDelayTimeListBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeGetImageInfo", nullptr, JSImageSoureNativeGetImageInfo, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeGetImageInfoBadParameter", nullptr, JSImageSoureNativeGetImageInfoBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeGetImagePropertyBadParameter", nullptr, JSImageSoureNativeGetImagePropertyBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},

    {"jsImageSoureNativeGetImagePropertyAllocFailed", nullptr, JSImageSoureNativeGetImagePropertyAllocFailed, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeGetImagePropertyWithNullInvaildParamter", nullptr,
     JSImageSoureNativeGetImagePropertyWithNullInvaildParamter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeModifyImageProperty", nullptr, JSImageSoureNativeModifyImageProperty, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeModifyImagePropertyBadParameter", nullptr, JSImageSoureNativeModifyImagePropertyBadParameter,
     nullptr, nullptr, nullptr, napi_default, nullptr},

    {"jsImageSoureNativeGetFrameCount", nullptr, JSImageSoureNativeGetFrameCount, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeGetFrameCountBadParameter", nullptr, JSImageSoureNativeGetFrameCountBadParameter, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeRelease", nullptr, JSImageSoureNativeRelease, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeReleaseBadParameter", nullptr, JSImageSoureNativeReleaseBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureCreateBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureCreateBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureGetDesiredAuxiliaryPictures", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureGetDesiredAuxiliaryPictures, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureGetDesiredAuxiliaryPicturesBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureGetDesiredAuxiliaryPicturesBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureSetDesiredAuxiliaryPictures", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureSetDesiredAuxiliaryPictures, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureSetDesiredAuxiliaryPicturesBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureSetDesiredAuxiliaryPicturesBadParameter, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureRelease", nullptr, JSImageSoureNativeDecodingOptionsForPictureRelease,
     nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeDecodingOptionsForPictureReleaseBadParameter", nullptr,
     JSImageSoureNativeDecodingOptionsForPictureReleaseBadParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"jsImageSoureNativeGetSupportedFormats", nullptr, JSImageSoureNativeGetSupportedFormats, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"jsImageSoureNativeGetSupportedFormatsInvalidParameter", nullptr,
     JSImageSoureNativeGetSupportedFormatsInvalidParameter, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_CreatePicture", nullptr,
     Test_PictureNative_CreatePicture, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_GetMainPixelmap", nullptr,
     Test_OH_PictureNative_GetMainPixelmap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_GetHdrComposedPixelmap", nullptr,
     Test_OH_PictureNative_GetHdrComposedPixelmap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_GetGainmapPixelmap", nullptr,
     Test_OH_PictureNative_GetGainmapPixelmap, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_SetAuxiliaryPicture", nullptr,
     Test_OH_PictureNative_SetAuxiliaryPicture, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_GetAuxiliaryPicture", nullptr,
     Test_OH_PictureNative_GetAuxiliaryPicture, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_GetMetadata", nullptr,
     Test_OH_PictureNative_GetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_SetMetadata", nullptr,
     Test_OH_PictureNative_SetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testPictureNative_Release", nullptr,
     Test_OH_PictureNative_Release, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNativeWritePixelsImage", nullptr,
     Test_OH_AuxiliaryPictureNativeWritePixelsImage, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_ReadPixels", nullptr,
     Test_OH_AuxiliaryPictureNative_ReadPixels, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_GetType", nullptr,
     Test_OH_AuxiliaryPictureNative_GetType, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_GetInfo", nullptr,
     Test_OH_AuxiliaryPictureNative_GetInfo, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_SetInfo", nullptr,
     Test_OH_AuxiliaryPictureNative_SetInfo, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_GetMetadata", nullptr,
     Test_OH_AuxiliaryPictureNative_GetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"testAuxiliaryPictureNative_SetMetadata", nullptr,
     Test_OH_AuxiliaryPictureNative_SetMetadata, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapCreatePixelMapResultSuccess", nullptr, PixelMapCreatePixelMapResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapGetBytesNumberPerRowResultSuccess", nullptr, PixelMapGetBytesNumberPerRowResultSuccess, nullptr, nullptr,
     nullptr, napi_default, nullptr},
    {"PixelMapGetIsEditableResultSuccess", nullptr, PixelMapGetIsEditableResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapIsSupportAlphaResultSuccess", nullptr, PixelMapIsSupportAlphaResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapSetAlphaAbleResultSuccess", nullptr, PixelMapSetAlphaAbleResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapGetDensityResultSuccess", nullptr, PixelMapGetDensityResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapSetOpacityResultSuccess", nullptr, PixelMapSetOpacityResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapScaleResultSuccess", nullptr, PixelMapScaleResultSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelMapScaleWithAntiAliasingResultSuccess", nullptr, PixelMapScaleWithAntiAliasingResultSuccess, nullptr,
     nullptr, nullptr, napi_default, nullptr},
    {"PixelMapTranslateResultSuccess", nullptr, PixelMapTranslateResultSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelMapRotateResultSuccess", nullptr, PixelMapRotateResultSuccess, nullptr, nullptr, nullptr, napi_default,
     nullptr},
    {"PixelMapFlipResultSuccess", nullptr, PixelMapFlipResultSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapCropResultSuccess", nullptr, PixelMapCropResultSuccess, nullptr, nullptr, nullptr, napi_default, nullptr},
    {"PixelMapGetImageInfoResultSuccess", nullptr, PixelMapGetImageInfoResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapAccessPixelsResultSuccess", nullptr, PixelMapAccessPixelsResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapUnAccessPixelsResultSuccess", nullptr, PixelMapUnAccessPixelsResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    {"PixelMapSetDensityResultSuccess", nullptr, PixelMapSetDensityResultSuccess, nullptr, nullptr, nullptr,
     napi_default, nullptr},
    };

static napi_value Init(napi_env env, napi_value exports)
{
    addImageProcessingTest(desc);
    napi_define_properties(env, exports, desc.size(), desc.data());
    return exports;
}
EXTERN_C_END

static napi_module demoModule = {
    .nm_version = 1,
    .nm_flags = 0,
    .nm_filename = nullptr,
    .nm_register_func = Init,
    .nm_modname = "entry",
    .nm_priv = ((void *)0),
    .reserved = {0},
};

extern "C" __attribute__((constructor)) void RegisterModule(void) { napi_module_register(&demoModule); }
