/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FUNC2_TEST_H
#define FUNC2_TEST_H

namespace OHOS {
namespace Media {

namespace Func2Test {
void SetUpTestCase();
}

int VIDEO_DECODE_SYNC_FUNC_0010();
int VIDEO_DECODE_SYNC_FUNC_0020();
int VIDEO_DECODE_SYNC_FUNC_0030();
int VIDEO_DECODE_SYNC_FUNC_0040();
int VIDEO_DECODE_SYNC_FUNC_0050();
int VIDEO_DECODE_SYNC_FUNC_0060();
int VIDEO_DECODE_SYNC_FUNC_0070();
int VIDEO_DECODE_SYNC_FUNC_0080();
int VIDEO_DECODE_SYNC_FUNC_0090();
int VIDEO_DECODE_SYNC_FUNC_0100();
int VIDEO_DECODE_SYNC_FUNC_0110();
int VIDEO_DECODE_SYNC_FUNC_0120();
int VIDEO_DECODE_SYNC_FUNC_0130();
int VIDEO_DECODE_SYNC_FUNC_0140();
int VIDEO_DECODE_SYNC_FUNC_0150();
int VIDEO_DECODE_SYNC_FUNC_0160();
int VIDEO_DECODE_SYNC_FUNC_0170();
int VIDEO_DECODE_SYNC_HW264_FUNC_0010();
int VIDEO_DECODE_SYNC_HW264_FUNC_0020();
int VIDEO_DECODE_SYNC_HW265_FUNC_0010();
int VIDEO_DECODE_SYNC_HW265_FUNC_0020();
int VIDEO_DECODE_SYNC_HW265_FUNC_0040();
int VIDEO_DECODE_SYNC_HW266_FUNC_0010();
int VIDEO_DECODE_SYNC_HW266_FUNC_0020();
int VIDEO_DECODE_SYNC_HW266_FUNC_0040();
int VIDEO_DECODE_SYNC_HW264_LOWLATENCY_FUNC_0010();
int VIDEO_DECODE_SYNC_HW265_LOWLATENCY_FUNC_0010();
int VIDEO_DECODE_SYNC_HW266_LOWLATENCY_FUNC_0010();
int VIDEO_DECODE_H264_BLANK_FRAME_0010();
int VIDEO_DECODE_H265_BLANK_FRAME_0020();
int VIDEO_DECODE_H266_BLANK_FRAME_0030();
int VIDEO_DECODE_LOW_LATENCY_0001();
int VIDEO_DECODE_LOW_LATENCY_0002();
int VIDEO_DECODE_LOW_LATENCY_0003();
int VIDEO_DECODE_LOW_LATENCY_0004();
int VIDEO_DECODE_LOW_LATENCY_0005();
int VIDEO_DECODE_LOW_LATENCY_0006();
int VIDEO_DECODE_LOW_LATENCY_0007();
int VIDEO_DECODE_LOW_LATENCY_0008();
int VIDEO_DECODE_LOW_LATENCY_0009();
int VIDEO_HWDEC_PIXE_FORMAT_0030();
int VIDEO_DECODE_TRANSFORM_0010();
int VIDEO_DECODE_TRANSFORM_0020();
int VIDEO_DECODE_RESOLUTION_0010();
int VIDEO_DECODE_ANOTHER_0010();
int VIDEO_CAPABILITY_CONFIG_0010();
int VIDEO_CAPABILITY_CONFIG_0020();
int VIDEO_CAPABILITY_CONFIG_0030();
} // namespace Media
} // namespace OHOS

#endif // FUNC2_TEST_H
