/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "include/NapiInitTestCommon.h"
#include "include/OhosCommonTest.h"
#include "napi/native_api.h"

// Include all function declarations from split header files
#include "include/NapiInitPart1Test.h"
#include "include/NapiInitPart2Test.h"
#include "include/NapiInitPart3Test.h"
#include "include/NapiInitPart4Test.h"
#include "include/NapiInitPart5Test.h"
#include "include/NapiInitPart6Test.h"

// Merge all descriptors
static const napi_property_descriptor g_mindsporeDescriptors[] = {
    // From NapiInitTest_Part1
    DECL_NAPI_DESC(AbsBuildTest),
    DECL_NAPI_DESC(AbsModelFinish),
    DECL_NAPI_DESC(AbsModelSetOperandValue),
    DECL_NAPI_DESC(AbsModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(AbsModelModelAddOperation),
    DECL_NAPI_DESC(AllBuildTest),
    DECL_NAPI_DESC(AllModelFinish),
    DECL_NAPI_DESC(AllModelSetOperandValue),
    DECL_NAPI_DESC(AllModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(AllModelModelAddOperation),
    DECL_NAPI_DESC(AssertBuildTest),
    DECL_NAPI_DESC(AssertModelFinish),
    DECL_NAPI_DESC(AssertModelSetOperandValue),
    DECL_NAPI_DESC(AssertModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(AssertModelModelAddOperation),
    DECL_NAPI_DESC(BroadcastToBuildTest),
    DECL_NAPI_DESC(BroadcastToModelFinish),
    DECL_NAPI_DESC(BroadcastToModelSetOperandValue),
    DECL_NAPI_DESC(BroadcastToModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(BroadcastToModelModelAddOperation),
    DECL_NAPI_DESC(CeilBuildTest),
    DECL_NAPI_DESC(CeilModelFinish),
    DECL_NAPI_DESC(CeilModelSetOperandValue),
    DECL_NAPI_DESC(CeilModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(CeilModelModelAddOperation),
    DECL_NAPI_DESC(CropBuildTest),
    DECL_NAPI_DESC(CropModelFinish),
    DECL_NAPI_DESC(CropModelSetOperandValue),
    DECL_NAPI_DESC(CropModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(CropModelModelAddOperation),
    DECL_NAPI_DESC(ClipBuildTest),
    DECL_NAPI_DESC(ClipModelFinish),
    DECL_NAPI_DESC(ClipModelSetOperandValue),
    DECL_NAPI_DESC(ClipModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ClipModelModelAddOperation),
    DECL_NAPI_DESC(ConstantOfShapeBuildTest),
    DECL_NAPI_DESC(ConstantOfShapeModelFinish),
    DECL_NAPI_DESC(ConstantOfShapeModelSetOperandValue),
    DECL_NAPI_DESC(ConstantOfShapeModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ConstantOfShapeModelModelAddOperation),
    DECL_NAPI_DESC(CosBuildTest),
    DECL_NAPI_DESC(CosModelFinish),
    DECL_NAPI_DESC(CosModelSetOperandValue),
    DECL_NAPI_DESC(CosModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(CosModelModelAddOperation),
    DECL_NAPI_DESC(DepthToSpaceBuildTest),
    // From NapiInitTest_Part2
    DECL_NAPI_DESC(DepthToSpaceModelFinish),
    DECL_NAPI_DESC(DepthToSpaceModelSetOperandValue),
    DECL_NAPI_DESC(DepthToSpaceModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(DepthToSpaceModelModelAddOperation),
    DECL_NAPI_DESC(DetectionPostProcessBuildTest),
    DECL_NAPI_DESC(DetectionPostProcessModelFinish),
    DECL_NAPI_DESC(DetectionPostProcessModelSetOperandValue),
    DECL_NAPI_DESC(DetectionPostProcessModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(DetectionPostProcessModelModelAddOperation),
    // OHOS NNRT OPS EQUAL
    DECL_NAPI_DESC(EqualBuildTest),
    DECL_NAPI_DESC(EqualModelFinish),
    DECL_NAPI_DESC(EqualModelSetOperandValue),
    DECL_NAPI_DESC(EqualModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(EqualModelModelAddOperation),
    // OHOS NNRT OPS ERF
    DECL_NAPI_DESC(ErfBuildTest),
    DECL_NAPI_DESC(ErfModelFinish),
    DECL_NAPI_DESC(ErfModelSetOperandValue),
    DECL_NAPI_DESC(ErfModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ErfModelModelAddOperation),
    // OHOS NNRT OPS EXP
    DECL_NAPI_DESC(ExpBuildTest),
    DECL_NAPI_DESC(ExpModelFinish),
    DECL_NAPI_DESC(ExpModelSetOperandValue),
    DECL_NAPI_DESC(ExpModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ExpModelModelAddOperation),
    // OHOS NNRT OPS FLATTEN
    // From NapiInitTest_Part3
    DECL_NAPI_DESC(FlattenBuildTest),
    DECL_NAPI_DESC(FlattenModelFinish),
    DECL_NAPI_DESC(FlattenModelSetOperandValue),
    DECL_NAPI_DESC(FlattenModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(FlattenModelModelAddOperation),
    // OHOS NNRT OPS FLOOR
    DECL_NAPI_DESC(FloorBuildTest),
    DECL_NAPI_DESC(FloorModelFinish),
    DECL_NAPI_DESC(FloorModelSetOperandValue),
    DECL_NAPI_DESC(FloorModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(FloorModelModelAddOperation),
    // OHOS NNRT OPS GATHERND
    DECL_NAPI_DESC(GatherNDBuildTest),
    DECL_NAPI_DESC(GatherNDModelFinish),
    DECL_NAPI_DESC(GatherNDModelSetOperandValue),
    DECL_NAPI_DESC(GatherNDModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(GatherNDModelModelAddOperation),
    // OHOS NNRT OPS GREATEREQUAL
    DECL_NAPI_DESC(GreaterEqualBuildTest),
    DECL_NAPI_DESC(GreaterEqualModelFinish),
    DECL_NAPI_DESC(GreaterEqualModelSetOperandValue),
    DECL_NAPI_DESC(GreaterEqualModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(GreaterEqualModelModelAddOperation),
    // OHOS NNRT OPS GREATER
    DECL_NAPI_DESC(GreaterBuildTest),
    DECL_NAPI_DESC(GreaterModelFinish),
    DECL_NAPI_DESC(GreaterModelSetOperandValue),
    DECL_NAPI_DESC(GreaterModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(GreaterModelModelAddOperation),
    // OHOS NNRT OPS HARDSIGMOID
    DECL_NAPI_DESC(HardSigmoidBuildTest),
    DECL_NAPI_DESC(HardSigmoidModelFinish),
    DECL_NAPI_DESC(HardSigmoidModelSetOperandValue),
    DECL_NAPI_DESC(HardSigmoidModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(HardSigmoidModelModelAddOperation),
    DECL_NAPI_DESC(InstanceNormBuildTest),
    DECL_NAPI_DESC(InstanceNormModelFinish),
    DECL_NAPI_DESC(InstanceNormModelSetOperandValue),
    DECL_NAPI_DESC(InstanceNormModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(InstanceNormModelModelAddOperation),
    DECL_NAPI_DESC(L2NormalizeBuildTest),
    DECL_NAPI_DESC(L2NormalizeModelFinish),
    DECL_NAPI_DESC(L2NormalizeModelSetOperandValue),
    DECL_NAPI_DESC(L2NormalizeModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(L2NormalizeModelModelAddOperation),
    DECL_NAPI_DESC(LeakyReluBuildTest),
    DECL_NAPI_DESC(LeakyReluModelFinish),
    DECL_NAPI_DESC(LeakyReluModelSetOperandValue),
    DECL_NAPI_DESC(LeakyReluModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LeakyReluModelModelAddOperation),
    // OHOS NNRT OPS LESS
    DECL_NAPI_DESC(LessBuildTest),
    DECL_NAPI_DESC(LessModelFinish),
    DECL_NAPI_DESC(LessModelSetOperandValue),
    DECL_NAPI_DESC(LessModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LessModelModelAddOperation),
    // OHOS NNRT OPS LOGICAL_AND
    DECL_NAPI_DESC(LogicalAndBuildTest),
    DECL_NAPI_DESC(LogicalAndModelFinish),
    DECL_NAPI_DESC(LogicalAndModelSetOperandValue),
    DECL_NAPI_DESC(LogicalAndModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LogicalAndModelModelAddOperation),
    // OHOS NNRT OPS LOGICAL_NOT
    DECL_NAPI_DESC(LogicalNotBuildTest),
    DECL_NAPI_DESC(LogicalNotModelFinish),
    DECL_NAPI_DESC(LogicalNotModelSetOperandValue),
    DECL_NAPI_DESC(LogicalNotModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LogicalNotModelModelAddOperation),
    // OHOS NNRT OPS LOG_SOFTMAX
    // From NapiInitTest_Part4
    DECL_NAPI_DESC(LogSoftmaxBuildTest),
    DECL_NAPI_DESC(LogSoftmaxModelFinish),
    DECL_NAPI_DESC(LogSoftmaxModelSetOperandValue),
    DECL_NAPI_DESC(LogSoftmaxModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LogSoftmaxModelModelAddOperation),
    // OHOS NNRT OPS LOG
    DECL_NAPI_DESC(LogBuildTest),
    DECL_NAPI_DESC(LogModelFinish),
    DECL_NAPI_DESC(LogModelSetOperandValue),
    DECL_NAPI_DESC(LogModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LogModelModelAddOperation),
    DECL_NAPI_DESC(LogicalOrBuildTest),
    DECL_NAPI_DESC(LogicalOrModelFinish),
    DECL_NAPI_DESC(LogicalOrModelSetOperandValue),
    DECL_NAPI_DESC(LogicalOrModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LogicalOrModelModelAddOperation),
    DECL_NAPI_DESC(LrnBuildTest),
    DECL_NAPI_DESC(LrnModelFinish),
    DECL_NAPI_DESC(LrnModelSetOperandValue),
    DECL_NAPI_DESC(LrnModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LrnModelModelAddOperation),
    DECL_NAPI_DESC(LstmBuildTest),
    DECL_NAPI_DESC(LstmModelFinish),
    DECL_NAPI_DESC(LstmModelSetOperandValue),
    DECL_NAPI_DESC(LstmModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(LstmModelModelAddOperation),
    DECL_NAPI_DESC(MinimumBuildTest),
    DECL_NAPI_DESC(MinimumModelFinish),
    DECL_NAPI_DESC(MinimumModelSetOperandValue),
    DECL_NAPI_DESC(MinimumModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(MinimumModelModelAddOperation),
    DECL_NAPI_DESC(ModBuildTest),
    DECL_NAPI_DESC(ModModelFinish),
    DECL_NAPI_DESC(ModModelSetOperandValue),
    DECL_NAPI_DESC(ModModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ModModelModelAddOperation),
    DECL_NAPI_DESC(NegBuildTest),
    DECL_NAPI_DESC(NegModelFinish),
    DECL_NAPI_DESC(NegModelSetOperandValue),
    DECL_NAPI_DESC(NegModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(NegModelModelAddOperation),
    DECL_NAPI_DESC(NotEqualBuildTest),
    // From NapiInitTest_Part5
    DECL_NAPI_DESC(NotEqualModelFinish),
    DECL_NAPI_DESC(NotEqualModelSetOperandValue),
    DECL_NAPI_DESC(NotEqualModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(NotEqualModelModelAddOperation),
    DECL_NAPI_DESC(PowBuildTest),
    DECL_NAPI_DESC(PowModelFinish),
    DECL_NAPI_DESC(PowModelSetOperandValue),
    DECL_NAPI_DESC(PowModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(PowModelModelAddOperation),
    DECL_NAPI_DESC(QuantDtypeCastBuildTest),
    DECL_NAPI_DESC(QuantDtypeCastModelFinish),
    DECL_NAPI_DESC(QuantDtypeCastModelSetOperandValue),
    DECL_NAPI_DESC(QuantDtypeCastModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(QuantDtypeCastModelModelAddOperation),
    DECL_NAPI_DESC(RangeBuildTest),
    DECL_NAPI_DESC(RangeModelFinish),
    DECL_NAPI_DESC(RangeModelSetOperandValue),
    DECL_NAPI_DESC(RangeModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(RangeModelModelAddOperation),
    DECL_NAPI_DESC(RankBuildTest),
    DECL_NAPI_DESC(RankModelFinish),
    DECL_NAPI_DESC(RankModelSetOperandValue),
    DECL_NAPI_DESC(RankModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(RankModelModelAddOperation),
    DECL_NAPI_DESC(ReciprocalBuildTest),
    DECL_NAPI_DESC(ReciprocalModelFinish),
    DECL_NAPI_DESC(ReciprocalModelSetOperandValue),
    DECL_NAPI_DESC(ReciprocalModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ReciprocalModelModelAddOperation),
    DECL_NAPI_DESC(Reducel2BuildTest),
    DECL_NAPI_DESC(Reducel2ModelFinish),
    DECL_NAPI_DESC(Reducel2ModelSetOperandValue),
    DECL_NAPI_DESC(Reducel2ModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(Reducel2ModelModelAddOperation),
    DECL_NAPI_DESC(ReducemaxBuildTest),
    DECL_NAPI_DESC(ReducemaxModelFinish),
    DECL_NAPI_DESC(ReducemaxModelSetOperandValue),
    DECL_NAPI_DESC(ReducemaxModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ReducemaxModelModelAddOperation),
    DECL_NAPI_DESC(ReduceminBuildTest),
    DECL_NAPI_DESC(ReduceminModelFinish),
    DECL_NAPI_DESC(ReduceminModelSetOperandValue),
    DECL_NAPI_DESC(ReduceminModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ReduceminModelModelAddOperation),
    DECL_NAPI_DESC(ReducesumBuildTest),
    DECL_NAPI_DESC(ReducesumModelFinish),
    DECL_NAPI_DESC(ReducesumModelSetOperandValue),
    DECL_NAPI_DESC(ReducesumModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ReducesumModelModelAddOperation),
    DECL_NAPI_DESC(RoundBuildTest),
    DECL_NAPI_DESC(RoundModelFinish),
    DECL_NAPI_DESC(RoundModelSetOperandValue),
    DECL_NAPI_DESC(RoundModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(RoundModelModelAddOperation),
    DECL_NAPI_DESC(ScatterndBuildTest),
    DECL_NAPI_DESC(ScatterndModelFinish),
    DECL_NAPI_DESC(ScatterndModelSetOperandValue),
    DECL_NAPI_DESC(ScatterndModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(ScatterndModelModelAddOperation),
    DECL_NAPI_DESC(SelectBuildTest),
    DECL_NAPI_DESC(SelectModelFinish),
    DECL_NAPI_DESC(SelectModelSetOperandValue),
    DECL_NAPI_DESC(SelectModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SelectModelModelAddOperation),
    DECL_NAPI_DESC(SinBuildTest),
    // From NapiInitTest_Part6
    DECL_NAPI_DESC(SinModelFinish),
    DECL_NAPI_DESC(SinModelSetOperandValue),
    DECL_NAPI_DESC(SinModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SinModelModelAddOperation),
    DECL_NAPI_DESC(SpacetodepthBuildTest),
    DECL_NAPI_DESC(SpacetodepthModelFinish),
    DECL_NAPI_DESC(SpacetodepthModelSetOperandValue),
    DECL_NAPI_DESC(SpacetodepthModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SpacetodepthModelModelAddOperation),
    DECL_NAPI_DESC(SparsetodenseBuildTest),
    DECL_NAPI_DESC(SparsetodenseModelFinish),
    DECL_NAPI_DESC(SparsetodenseModelSetOperandValue),
    DECL_NAPI_DESC(SparsetodenseModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SparsetodenseModelModelAddOperation),
    DECL_NAPI_DESC(SquareBuildTest),
    DECL_NAPI_DESC(SquareModelFinish),
    DECL_NAPI_DESC(SquareModelSetOperandValue),
    DECL_NAPI_DESC(SquareModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SquareModelModelAddOperation),
    DECL_NAPI_DESC(SwishBuildTest),
    DECL_NAPI_DESC(SwishModelFinish),
    DECL_NAPI_DESC(SwishModelSetOperandValue),
    DECL_NAPI_DESC(SwishModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(SwishModelModelAddOperation),
    DECL_NAPI_DESC(UnstackBuildTest),
    DECL_NAPI_DESC(UnstackModelFinish),
    DECL_NAPI_DESC(UnstackModelSetOperandValue),
    DECL_NAPI_DESC(UnstackModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(UnstackModelModelAddOperation),
    DECL_NAPI_DESC(WhereBuildTest),
    DECL_NAPI_DESC(WhereModelFinish),
    DECL_NAPI_DESC(WhereModelSetOperandValue),
    DECL_NAPI_DESC(WhereModelModelSpecifyInputsAndOutputs),
    DECL_NAPI_DESC(WhereModelModelAddOperation),
};

EXTERN_C_START static napi_value Init(napi_env env, napi_value exports)
{
    napi_define_properties(env,
                           exports,
                           sizeof(g_mindsporeDescriptors) / sizeof(g_mindsporeDescriptors[0]),
                           g_mindsporeDescriptors);
    return exports;
}
EXTERN_C_END

static napi_module nncoreopsModule = {
    .nm_version = 1,
    .nm_flags = 0,
    .nm_filename = nullptr,
    .nm_register_func = Init,
    .nm_modname = "nncoreops",
    .nm_priv = ((void*)0),
    .reserved = { 0 },
};

extern "C" __attribute__((constructor)) void RegisterEntryModule(void)
{
    napi_module_register(&nncoreopsModule);
}
