/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Audio Stream Builder Test Native API
 * 
 * @param testCaseNumber - Test case number (0-48)
 * @returns Test result: 0 for success, -1 for failure
 */
export const audioStreamBuilderTest: (testCaseNumber: number) => number;

/**
 * Test case number enumeration
 */
export enum TestCaseNumber {
  TEST_CASE_CREATE_001 = 0,
  TEST_CASE_CREATE_002 = 1,
  TEST_CASE_DESTROY_001 = 2,
  TEST_CASE_SET_PARAMETER_001 = 3,
  TEST_CASE_SET_PARAMETER_002 = 4,
  TEST_CASE_SET_PARAMETER_003 = 5,
  TEST_CASE_SET_PARAMETER_004 = 6,
  TEST_CASE_SET_PARAMETER_005 = 7,
  TEST_CASE_SET_PARAMETER_006 = 8,
  TEST_CASE_SET_PARAMETER_007 = 9,
  TEST_CASE_SET_PARAMETER_008 = 10,
  TEST_CASE_SET_PARAMETER_009 = 11,
  TEST_CASE_SET_PARAMETER_010 = 12,
  TEST_CASE_SET_PARAMETER_011 = 13,
  TEST_CASE_SET_PARAMETER_012 = 14,
  TEST_CASE_SET_PARAMETER_013 = 15,
  TEST_CASE_SET_PARAMETER_014 = 16,
  TEST_CASE_SET_PARAMETER_015 = 17,
  TEST_CASE_SET_PARAMETER_016 = 18,
  TEST_CASE_SET_PARAMETER_017 = 19,
  TEST_CASE_SET_PARAMETER_018 = 20,
  TEST_CASE_SET_PARAMETER_019 = 21,
  TEST_CASE_SET_PARAMETER_020 = 22,
  TEST_CASE_SET_RENDERER_PRIVACY_001 = 23,
  TEST_CASE_SET_RENDERER_PRIVACY_002 = 24,
  TEST_CASE_SET_RENDERER_PRIVACY_003 = 25,
  TEST_CASE_SET_SAMPLE_FORMAT_001 = 26,
  TEST_CASE_SET_SAMPLE_FORMAT_002 = 27,
  TEST_CASE_SET_SAMPLE_FORMAT_003 = 28,
  TEST_CASE_SET_SAMPLE_FORMAT_004 = 29,
  TEST_CASE_SET_SAMPLE_FORMAT_005 = 30,
  TEST_CASE_SET_LATENCY_MODE_001 = 31,
  TEST_CASE_SET_CAPTURER_INFO_001 = 32,
  TEST_CASE_SET_CAPTURER_INFO_002 = 33,
  TEST_CASE_SET_RENDERER_INFO_001 = 34,
  TEST_CASE_SET_RENDERER_INFO_002 = 35,
  TEST_CASE_SET_RENDERER_INFO_003 = 36,
  TEST_CASE_SET_CHANNEL_LAYOUT_001 = 37,
  TEST_CASE_SET_WRITE_DATA_WITH_METADATA_CALLBACK_001 = 38,
  TEST_CASE_SET_INTERRUPT_MODE_001 = 39,
  TEST_CASE_SET_INTERRUPT_MODE_002 = 40,
  TEST_CASE_SET_INTERRUPT_MODE_003 = 41,
  TEST_CASE_SET_INTERRUPT_MODE_006 = 42,
  TEST_CASE_SET_RENDERER_INTERRUPT_MODE_004 = 43,
  TEST_CASE_SET_RENDERER_INTERRUPT_MODE_005 = 44,
  TEST_CASE_SET_RENDERER_WRITE_DATA_CALLBACK_001 = 45,
  TEST_CASE_SET_RENDERER_WRITE_DATA_CALLBACK_002 = 46,
  TEST_CASE_SET_RENDERER_WRITE_DATA_CALLBACK_003 = 47,
  TEST_CASE_SET_RENDERER_WRITE_DATA_CALLBACK_004 = 48
}