/*
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <climits>
#include <gtest/gtest.h>
#include "../Khrgles31BaseFunc.h"
#include "../ActsGles31KhrMainUncover0001TestSuite.h"
#include "shrinkdefine.h"

using namespace std;
using namespace testing::ext;
using namespace OHOS;

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000590,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000591,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000592,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000593,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000594,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000595,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000596,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000597,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000598,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000599,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000600,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000601,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000602,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000603,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000604,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000605,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_isolines_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000606,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000607,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000608,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000609,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000610,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000611,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000612,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000613,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_isolines_vertex_ordering__vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000614,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000615,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000616,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000617,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000618,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000619,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000620,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000621,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000622,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000623,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_P",
 "osition_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000624,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000625,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000626,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000627,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000628,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000629,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVer",
 "tices_Position_PointSize_primitive_mode_quads_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000630,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_",
 "Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000631,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_",
 "Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000632,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000633,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000634,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posit",
 "ion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000635,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posi",
 "tion_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000636,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVer",
 "tices_Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000637,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVe",
 "rtices_Position_PointSize_primitive_mode_quads_vertex_ordering__vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000638,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Posi",
 "tion_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000639,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000640,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position_",
 "PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000641,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000642,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000643,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000644,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000645,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_ccw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000646,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000647,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Pos",
 "ition_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000648,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000649,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000650,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Position",
 "_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000651,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000652,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertic",
 "es_Position_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000653,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_triangles_vertex_ordering_cw_vertex_spacing__point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000654,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_equal_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000655,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Po",
 "sition_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_equal_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000656,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000657,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_even_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000658,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positio",
 "n_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000659,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVertices_Positi",
 "on_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing_fractional_odd_spacing_point_mode_enabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000660,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVerti",
 "ces_Position_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing__point_mode_disabled");

static SHRINK_HWTEST_F(ActsGles31KhrMainUncover0001TestSuite, TestCase_000661,
 "KHR-GLES31.core.tessellation_shader.tessellation_control_to_tessellation_evaluation.gl_MaxPatchVert",
 "ices_Position_PointSize_primitive_mode_triangles_vertex_ordering__vertex_spacing__point_mode_enabled");
